const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
process.env.SATTVA_DADOS = fs.mkdtempSync(path.join(os.tmpdir(), 'sattva-credito-cbs-'));
const { avaliarCredito } = require('../src/engine/motor');
const cls = { status: 'CLASSIFICADO' };
const regular = avaliarCredito({ regimeAdquirente: 'lucro_real', regimeFornecedor: 'lucro_real', cls });
assert.deepEqual([regular.tipoCredito, regular.statusDeterminacao], ['NORMAL', 'DETERMINADO']);
const simplesConhecido = avaliarCredito({ regimeAdquirente: 'lucro_real', regimeFornecedor: 'simples_nacional', cls, simplesFornecedorConhecido: true });
assert.deepEqual([simplesConhecido.tipoCredito, simplesConhecido.modalidadeCredito, simplesConhecido.statusDeterminacao], ['SIMPLES', 'LIMITADO_CBS_SIMPLES', 'DETERMINADO']);
const simplesIndeterminado = avaliarCredito({ regimeAdquirente: 'lucro_real', regimeFornecedor: 'simples_nacional', cls, simplesFornecedorConhecido: false });
assert.deepEqual([simplesIndeterminado.tipoCredito, simplesIndeterminado.statusDeterminacao], ['SIMPLES', 'INDETERMINADO']);
const meiPresumido = avaliarCredito({ regimeAdquirente: 'lucro_real', regimeFornecedor: 'mei', cls: { ...cls, creditoPresumido: true } });
assert.deepEqual([meiPresumido.tipoCredito, meiPresumido.statusDeterminacao], ['PRESUMIDO', 'DETERMINADO']);
const meiSemHipotese = avaliarCredito({ regimeAdquirente: 'lucro_real', regimeFornecedor: 'mei', cls });
assert.deepEqual([meiSemHipotese.tipoCredito, meiSemHipotese.statusDeterminacao], ['SEM_CREDITO', 'DETERMINADO']);
const insuficiente = avaliarCredito({ regimeAdquirente: 'lucro_real', regimeFornecedor: null, cls });
assert.equal(insuficiente.statusDeterminacao, 'INDETERMINADO');
assert.notEqual(insuficiente.tipoCredito, 'SEM_CREDITO');
console.log('credito-cbs.test: seis cenários e indeterminado preservados');
