const assert=require('assert');
const fs=require('fs');
const path=require('path');
const raiz=path.resolve(__dirname,'..');
const db=fs.readFileSync(path.join(raiz,'src/db.js'),'utf8');
const api=fs.readFileSync(path.join(raiz,'src/routes/api.js'),'utf8');
const tela=fs.readFileSync(path.join(raiz,'public/js/telas.js'),'utf8');
const config=fs.readFileSync(path.join(raiz,'public/js/telas6.js'),'utf8');
const motor=fs.readFileSync(path.join(raiz,'src/services/motorExec.js'),'utf8');
const classificador=fs.readFileSync(path.join(raiz,'src/engine/classificador.js'),'utf8');
const persistencia=fs.readFileSync(path.join(raiz,'src/services/questorPersistencia.js'),'utf8');
const migration=fs.readFileSync(path.join(raiz,'supabase/migrations/20261014_questor_razao_previas_duraveis.sql'),'utf8');

for (const chave of ['LICENCA_USO_SISTEMAS_SOFTWARE','MATERIAL_ESCRITORIO','ALUGUEL_IMOVEL_COMERCIAL','LOCACAO_VEICULOS','MATERIAL_LIMPEZA']) assert.match(db,new RegExp(chave));
assert.match(api,/router\.post\('\/empresas\/:id\/entradas-manuais'/);
assert.match(api,/router\.get\('\/empresas\/:id\/entradas-manuais'/);
assert.match(api,/fornecedores\/consultar-cnpj/,'entradas manuais precisam permitir prévia de fornecedor por CNPJ');
assert.match(api,/fornecedorPorCnpjConsultado/,'a prévia e a confirmação precisam reutilizar a mesma identificação do fornecedor');
assert.match(api,/CONSULTA_CNPJ_ENTRADA_MANUAL/,'o fornecedor consultado precisa permanecer rastreável na entrada manual');
assert.match(api,/publicarEntradasQuestorConciliadas\(empresaId,inseridos\.map/,'a entrada manual com CNPJ deve publicar fornecedor e lançamento pela chave estável');
assert.match(api,/router\.post\('\/config\/itens-entrada-manual'/);
assert.match(api,/exigirPeriodoParaImportacao/);
assert.match(api,/periodoAnalisado\.noPeriodo/);
assert.match(api,/MANUAL_ENTRADA/);
assert.match(api,/publicarOperacaoEmpresa/);
assert.match(tela,/grupoCentral === 'receitas'/);
assert.match(tela,/Lançar entrada manual/);
assert.match(tela,/Fornecedor pelo CNPJ \(opcional\)/,'o lançamento manual deve permitir consulta rápida de fornecedor por CNPJ');
assert.match(tela,/Consultar CNPJ/,'a interface deve disparar a consulta antes da confirmação');
assert.match(tela,/fila incremental/);
assert.match(config,/Itens de entrada manual/);
assert.match(config,/Adicionar item/);
assert.match(config,/Itens e regras por regime/);
assert.match(config,/PIS/);
assert.match(config,/Cofins/);
assert.match(api,/regimesPadraoEntrada/);
assert.match(api,/pis_lucro_real/);
assert.match(api,/percentualObrigatorio/);
assert.match(config,/Obrigatória para Lucro Real e Lucro Presumido/);
assert.match(api,/pis_cofins_percentual/);
assert.match(config,/PIS\/Cofins conjunto/);
assert.match(api,/referencia_pis_cofins/);
assert.match(api,/razao_identificador/,'a inclusão do Razão deve guardar a identidade estável da linha');
assert.match(api,/INCLUIDO_QUESTOR_RAZAO/,'a prévia salva deve distinguir linha já incluída do Razão');
assert.match(api,/recuperarPreviaRazao/,'antes de pedir arquivo novamente a rota restaura a última prévia durável');
assert.match(api,/publicarPreviaRazao\(empresaId\)/,'uma nova prévia é publicada no armazenamento compartilhado');
assert.match(persistencia,/async function publicarPreviaRazao/,'a persistência do Razão é explícita e durável');
assert.match(persistencia,/async function recuperarPreviaRazao/,'a prévia pode ser restaurada após reinício da instância');
assert.match(migration,/create table if not exists public\.questor_razao_previas/,'a prévia possui armazenamento compartilhado próprio');
assert.match(api,/publicarEntradasQuestorConciliadas\(empresaId,resultado\.movimento_ids\)/,'o Razão deve publicar pela rotina de chave estável');
assert.match(api,/DOCUMENTO_JA_REPRESENTADO_COM_MESMO_VALOR_E_COMPETENCIA/,'a inclusão não pode descartar NF apenas por coincidência de número');
assert.match(api,/baixarConfiguracao\(\['param_regras'\]\)/,'o item recém-cadastrado é restaurado antes da inclusão pelo Razão');
assert.match(api,/motivos:\{\}/,'a rota devolve o motivo de cada descarte em vez de informar zero silenciosamente');
assert.match(api,/replace\(\/\\D\/g,''\)/,'a contrapartida formatada deve ser normalizada integralmente, sem perder os dígitos após pontos');
assert.match(api,/CONTRAPARTIDA_QUESTOR/,'o vínculo pelo código de pessoa do Questor deve permanecer rastreável');
assert.match(api,/materializarFornecedorDaContrapartida/,'pessoa identificada no cadastro Questor deve virar fornecedor com CNPJ na inclusão ou releitura');
assert.match(api,/pessoasQuestorPelosHistoricos/,'quando a contrapartida não resolver, o histórico deve ser confrontado com nomepessoa');
assert.match(api,/HISTORICO_NOME_QUESTOR/,'o vínculo pelo nome do histórico deve preservar origem e evidência própria');
assert.match(api,/pessoaQuestorPorCnpj/,'códigos repetidos no cadastro Questor devem ser deduplicados pelo CNPJ antes da decisão');
assert.match(api,/NOME_ABREVIADO_QUESTOR/,'históricos que abreviam a razão social devem manter a evidência do critério usado');
assert.match(api,/ALIAS_TELECOM_TIM_QUESTOR/,'TIM no histórico deve ser reconhecida pelo alias de telecom controlado');
assert.match(api,/ALIAS_TELECOM_VIVO_QUESTOR/,'Vivo no histórico deve ser reconhecida pelo alias de telecom controlado');
assert.match(api,/ALIAS_TELECOM_ALGAR_QUESTOR/,'Algar Telecom deve ser vinculada somente pelo alias de telecom controlado');
assert.match(api,/HISTORICO_ALIAS_QUESTOR/,'o vínculo por denominação comercial deve ficar rastreável e distinto do nome literal');
assert.match(api,/identificados_por_historico/,'a releitura deve informar quantos fornecedores foram identificados pelo histórico');
assert.match(api,/reclassificar-naturezas/,'lançamentos já incluídos pelo Razão precisam poder reaplicar sua natureza');
assert.match(api,/LOCACAO_VEICULOS/,'locação de veículos deve ser separada de aluguel de imóvel');
assert.match(api,/Não classificar.*isolada.*imóvel/i,'a regra não pode tratar qualquer locação como imóvel');
assert.match(api,/db\.transaction\(\(\)=>\{ for\(const linha of selecionados\)/,'a inclusão é executada dentro de transação');
assert.match(api,/\}\}\)\(\);/,'a função transacional é invocada e não apenas criada');
assert.match(api,/listarEntradasQuestor/,'entradas manuais também devem ler inclusões Questor já publicadas na fonte compartilhada');
assert.match(api,/QUESTOR_CONCILIACAO_ENTRADA/,'a consulta manual preserva tanto o Razão quanto a conciliação direta do Questor');
assert.match(api,/entradasCompartilhadas/,'a cópia local não pode ser a única origem da listagem');
assert.match(api,/typeof x\.normalizacao_evidencia === 'object'/,'a evidência e a classificação sobrevivem à leitura JSON do PostgreSQL');
assert.match(tela,/referenciaPisCofinsEntradaManual/);
assert.match(tela,/Entradas manuais/);
assert.match(tela,/identificados_por_historico/,'a tela deve informar a identificação feita pelo histórico do Razão');
assert.match(tela,/Reaplicar natureza das entradas do Razão/,'a tela deve permitir corrigir as classificações já materializadas');
assert.match(tela,/Lançamentos manuais de entrada/);
assert.match(tela,/Questor · conciliada/,'a tela identifica a origem da conciliação direta do Questor');
const telasQuestor=fs.readFileSync(path.join(raiz,'public/js/telas2.js'),'utf8');
assert.match(telasQuestor,/Nenhum lançamento foi incluído/,'a interface não confirma sucesso quando a rota incluiu zero linhas');
assert.match(tela,/data-aba-cadeia/);
assert.match(tela,/NCM \$\{d\.ncm/);
assert.match(tela,/deixam o total de PIS\/Cofins/);
assert.match(tela,/carga atual no DAS/);
assert.doesNotMatch(tela,/Grau de repasse simulado/);
assert.match(tela,/Itens com crédito CBS/);
assert.match(tela,/Notas de entrada/);
assert.match(tela,/mostrarCreditosCbs/);
assert.doesNotMatch(tela,/data-aba-cadeia="creditos_cbs"/);
assert.doesNotMatch(tela,/data-aba-cadeia="notas_credito_cbs"/);
assert.match(tela,/Regime do fornecedor/);
assert.match(tela,/Antes — PIS\/Cofins/);
assert.match(api,/pis_cofins_atual/);
assert.match(api,/regimes_fornecedor/);
assert.match(motor,/entradaManual/);
assert.match(classificador,/lançamento manual de entrada/);
assert.match(classificador,/reducao_cbs:beneficio/);
assert.match(fs.readFileSync(path.join(raiz,'src/services/operacaoCompartilhada.js'),'utf8'),/MANUAL_ENTRADA/,'a publicação de entradas por chave estável deve aceitar a origem manual');
console.log('OK: entradas manuais são aditivas, limitadas ao período e publicadas na fonte compartilhada.');
