const assert=require('assert');
const fs=require('fs');
const path=require('path');
const raiz=path.resolve(__dirname,'..');
const db=fs.readFileSync(path.join(raiz,'src/db.js'),'utf8');
const api=fs.readFileSync(path.join(raiz,'src/routes/api.js'),'utf8');
const tela=fs.readFileSync(path.join(raiz,'public/js/telas.js'),'utf8');
const config=fs.readFileSync(path.join(raiz,'public/js/telas6.js'),'utf8');
const motor=fs.readFileSync(path.join(raiz,'src/services/motorExec.js'),'utf8');
const classificador=fs.readFileSync(path.join(raiz,'src/engine/classificador.js'),'utf8');

for (const chave of ['LICENCA_USO_SISTEMAS_SOFTWARE','MATERIAL_ESCRITORIO','ALUGUEL_IMOVEL_COMERCIAL','MATERIAL_LIMPEZA']) assert.match(db,new RegExp(chave));
assert.match(api,/router\.post\('\/empresas\/:id\/entradas-manuais'/);
assert.match(api,/router\.get\('\/empresas\/:id\/entradas-manuais'/);
assert.match(api,/router\.post\('\/config\/itens-entrada-manual'/);
assert.match(api,/exigirPeriodoParaImportacao/);
assert.match(api,/periodoAnalisado\.noPeriodo/);
assert.match(api,/MANUAL_ENTRADA/);
assert.match(api,/publicarOperacaoEmpresa/);
assert.match(tela,/grupoCentral === 'receitas'/);
assert.match(tela,/Lançar entrada manual/);
assert.match(tela,/fila incremental/);
assert.match(config,/Itens de entrada manual/);
assert.match(config,/Adicionar item/);
assert.match(config,/Itens e regras por regime/);
assert.match(config,/PIS/);
assert.match(config,/Cofins/);
assert.match(api,/regimesPadraoEntrada/);
assert.match(api,/pis_lucro_real/);
assert.match(api,/percentualObrigatorio/);
assert.match(config,/Obrigatória para Lucro Real e Lucro Presumido/);
assert.match(api,/pis_cofins_percentual/);
assert.match(config,/PIS\/Cofins conjunto/);
assert.match(api,/referencia_pis_cofins/);
assert.match(tela,/referenciaPisCofinsEntradaManual/);
assert.match(tela,/Entradas manuais/);
assert.match(tela,/Lançamentos manuais de entrada/);
assert.match(tela,/data-aba-cadeia/);
assert.match(tela,/NCM \$\{d\.ncm/);
assert.match(tela,/deixam o total de PIS\/Cofins/);
assert.match(tela,/carga atual no DAS/);
assert.doesNotMatch(tela,/Grau de repasse simulado/);
assert.match(tela,/Itens com crédito CBS/);
assert.match(tela,/Notas de entrada/);
assert.match(tela,/mostrarCreditosCbs/);
assert.doesNotMatch(tela,/data-aba-cadeia="creditos_cbs"/);
assert.doesNotMatch(tela,/data-aba-cadeia="notas_credito_cbs"/);
assert.match(tela,/Regime do fornecedor/);
assert.match(tela,/Antes — PIS\/Cofins/);
assert.match(api,/pis_cofins_atual/);
assert.match(api,/regimes_fornecedor/);
assert.match(motor,/entradaManual/);
assert.match(classificador,/lançamento manual de entrada/);
assert.match(classificador,/reducao_cbs:beneficio/);
console.log('OK: entradas manuais são aditivas, limitadas ao período e publicadas na fonte compartilhada.');
