const assert = require('node:assert/strict');
const fs = require('node:fs');

const leitor = fs.readFileSync(require.resolve('../src/services/documentosFiscaisCompartilhados'), 'utf8');
const api = fs.readFileSync(require.resolve('../src/routes/api'), 'utf8');
const telas = fs.readFileSync(require.resolve('../public/js/telas'), 'utf8');
const rotaNormal = api.slice(api.indexOf("router.get('/empresas/:id/documentos-fiscais'"), api.indexOf("router.get('/empresas/:id/documentos-fiscais/exportar'"));
const rotaExportacao = api.slice(api.indexOf("router.get('/empresas/:id/documentos-fiscais/exportar'"), api.indexOf("router.get('/empresas/:id/documentos-fiscais/sombra-compartilhada'"));
const rotaSombra = api.slice(api.indexOf("router.get('/empresas/:id/documentos-fiscais/sombra-compartilhada'"), api.indexOf("router.get('/empresas/:id/documentos-fiscais/:referencia'"));
const rotaOpcoesFiltros = api.slice(api.indexOf("router.get('/empresas/:id/documentos-fiscais/opcoes-filtros'"), api.indexOf("router.get('/empresas/:id/documentos-fiscais/sombra-compartilhada'"));

assert.match(leitor, /BEGIN READ ONLY/, 'leitor direto abre transação somente leitura');
assert.match(leitor, /ROLLBACK/, 'leitor direto encerra a leitura sem persistir mudanças');
assert.match(leitor, /new Pool\(/, 'leitor direto reutiliza conexões em vez de abrir uma por filtro');
assert.match(leitor, /max:4/, 'pool direto mantém concorrência limitada');
assert.match(leitor, /db\.release\(\)/, 'conexão é devolvida ao pool ao fim da leitura');
assert.match(leitor, /WITH resultado AS/, 'total e página são obtidos na mesma consulta');
assert.doesNotMatch(leitor, /const count = await db\.query/, 'leitor não faz uma consulta separada apenas para contar');
assert.doesNotMatch(leitor, /\b(INSERT|UPDATE|DELETE|CREATE|ALTER|DROP)\b/i, 'leitor direto não contém comandos de escrita ou estrutura');
assert.match(leitor, /m\.competencia=\$\$\{params\.length\}/, 'competência é aplicada antes da deduplicação');
assert.match(leitor, /m\.tipo=\$\$\{params\.length\}/, 'tipo é aplicado antes da deduplicação na leitura direta');
assert.match(leitor, /valor >= \$\$\{parametros\.length\}/, 'valor mínimo é filtrado na fonte antes da paginação');
assert.match(leitor, /valor <= \$\$\{parametros\.length\}/, 'valor máximo é filtrado na fonte antes da paginação');
assert.match(leitor, /normalizacao_evidencia/, 'a leitura direta preserva a evidência necessária à regra operacional');
assert.match(leitor, /situacao_documento/, 'a leitura direta preserva o estado fiscal do documento');
assert.match(leitor, /exportacao_limitada/, 'exportação direta nunca devolve planilha parcial silenciosamente');
assert.match(leitor, /leitura_metricas/, 'leitor retorna telemetria de latência sem persistir documentos');
assert.match(leitor, /async function listarOpcoesFiltros/, 'opções de filtro têm leitura própria, sem depender da página');
assert.match(leitor, /SELECT DISTINCT competencia/, 'competências vêm do conjunto completo da fonte');
assert.match(leitor, /SELECT DISTINCT UPPER\(COALESCE\(NULLIF\(modelo_documento_fiscal/, 'modelos vêm do conjunto completo da fonte');
assert.match(rotaSombra, /garantirEmpresaPermitida/, 'rota sombra exige sessão autorizada');
assert.match(rotaSombra, /documentosFiscaisCompartilhados/, 'rota sombra usa leitor isolado');
assert.match(rotaNormal, /reconciliarDocumentosFiscaisParaLeitura/, 'rota normal permanece inalterada durante a comparação');
assert.match(api, /LEITURA_DOCUMENTOS_COMPARTILHADA_ATIVA !== 'false'/, 'a fonte compartilhada é a referência por padrão e só desliga por contingência explícita');
assert.doesNotMatch(api, /LEITURA_DOCUMENTOS_COMPARTILHADA_EMPRESA_ID/, 'a leitura não pode ocultar empresas por uma lista experimental');
assert.doesNotMatch(api, /LEITURA_DOCUMENTOS_COMPARTILHADA_COMPETENCIA/, 'a leitura não pode ocultar competências por uma trava experimental');
assert.match(rotaNormal, /usando contingência local/, 'falha transitória da fonte compartilhada preserva a consulta local');
assert.match(rotaNormal, /receitaOperacional\.compoeReceita\(d\)/, 'a operação usa a mesma regra da leitura histórica');
assert.match(rotaExportacao, /leituraDocumentalDiretaControlada/, 'exportação direta respeita o mesmo escopo controlado da tela');
assert.match(rotaExportacao, /exportacao_limitada/, 'exportação acima do limite é bloqueada em vez de truncada');
assert.match(rotaOpcoesFiltros, /garantirEmpresaPermitida/, 'opções de filtro exigem sessão autorizada');
assert.doesNotMatch(rotaOpcoesFiltros, /reconciliarDocumentosFiscaisParaLeitura/, 'opções de filtro não disparam reconciliação ou processamento');
assert.match(telas, /Leitura direta em validação/, 'a interface identifica o recorte em validação');
assert.match(telas, /leitura_metricas/, 'a interface exibe telemetria da leitura controlada');
assert.match(telas, /opcoes-filtros\?sentido=/, 'tela carrega opções completas da aba separadamente da página');

console.log('leitura-documentos-compartilhada-sombra: isolamento e contrato somente-leitura: OK');
