const assert=require('assert'); const fs=require('fs'); const os=require('os'); const path=require('path');
const pasta=fs.mkdtempSync(path.join(os.tmpdir(),'sattva-mapa-')); process.env.SATTVA_DADOS=pasta;
const db=require('../src/db'); const mapa=require('../src/services/mapaOperacional');
const empresa=Number(db.prepare('INSERT INTO empresas (cnpj,razao_social,cnae,atividade,cnaes_secundarios) VALUES (?,?,?,?,?)').run('44444444000144','Mapa teste','6201501','Desenvolvimento de programas',JSON.stringify([{codigo:'6202300',descricao:'Desenvolvimento sob encomenda'}])).lastInsertRowid);
db.prepare('INSERT INTO base_ncm (ncm,descricao,tratamento_pis_cofins,pis_percentual,cofins_percentual,reducao_cbs) VALUES (?,?,?,?,?,?)').run('85171300','Telefone','MONOFASICO',1.65,7.6,0);
db.prepare('INSERT INTO pricing_products (empresa_id,codigo,descricao,ncm) VALUES (?,?,?,?)').run(empresa,'PROD-1','Telefone comercial','85171300');
db.prepare('INSERT INTO base_servicos (nbs,lc116,descricao_item,tratamento_pis_cofins,pis_percentual,cofins_percentual,reducao) VALUES (?,?,?,?,?,?,?)').run('115013000','1.05','Licenciamento de software','NORMAL',1.65,7.6,'integral');
db.prepare('INSERT INTO pricing_services (empresa_id,codigo,descricao,nbs,lc116) VALUES (?,?,?,?,?)').run(empresa,'SERV-1','Software','115013000','1.05');
const r=mapa.listar(empresa); assert.equal(r.cnaes.length,2); assert.equal(r.resumo.itens,2); assert.equal(r.resumo.com_regra,2); assert.ok(r.itens.some(x=>x.tipo==='NCM'&&x.tratamento_atual==='MONOFASICO')); assert.ok(r.aviso.includes('CNAE'));
db.close(); fs.rmSync(pasta,{recursive:true,force:true}); console.log('mapa-operacional.test.js: OK');
