const assert = require('node:assert/strict');
const fs = require('node:fs'); const path = require('node:path');
const fila = fs.readFileSync(path.join(__dirname, '../src/services/processamentoCarteira.js'), 'utf8');
const motor = fs.readFileSync(path.join(__dirname, '../src/services/motorExecucaoFila.js'), 'utf8');
const api = fs.readFileSync(path.join(__dirname, '../src/routes/api.js'), 'utf8');
const preparacao = fs.readFileSync(path.join(__dirname, '../src/services/preparacaoMotor.js'), 'utf8');
const operacao = fs.readFileSync(path.join(__dirname, '../src/services/operacaoCompartilhada.js'), 'utf8');
assert.match(motor, /const TIPO = 'MOTOR_COMPLETO'/);
assert.match(motor, /const TIPO_INCREMENTAL = 'MOTOR_INCREMENTAL'/);
assert.match(motor, /async function solicitarIncremental/);
assert.match(motor, /modo:'INCREMENTAL_IDS_EXPLICITOS'/);
assert.match(motor, /iniciarWorker: false/);
assert.match(motor, /from\('jobs_carteira'\)/);
assert.match(motor, /a fila compartilhada é a fonte de/i);
assert.match(motor, /if \(supabase\.configurado\(\)\) \{/);
assert.match(motor, /estado: job\.status, etapas: etapas\(job, null\)/);
assert.match(fila, /payload: JSON\.stringify\(opcoes\.payload/);
assert.match(fila, /const grupoId = String\(opcoes\.grupo_id \|\| id\(\)\)/);
assert.match(fila, /grupo_id: grupoId/);
assert.match(fila, /function resumirGrupo\(grupoId, jobs = \[\]\)/);
assert.match(fila, /Acompanhamento compartilhado da fila/);
assert.match(fila, /PROCESSAMENTO_CARTEIRA_CONCORRENCIA\) \|\| 1/);
assert.match(fila, /require\('\.\/preparacaoMotor'\)\.preparar\(job\.empresa_id\)/);
const ramoIncremental = fila.slice(fila.indexOf("if (job.tipo_job === 'MOTOR_INCREMENTAL')"), fila.indexOf('bases.classificarMovimentos(job.empresa_id)'));
assert.match(ramoIncremental, /movimento_ids/);
assert.match(ramoIncremental, /motorExec\.reprocessarIncremental/);
assert.doesNotMatch(ramoIncremental, /preparar\(job\.empresa_id\)/, 'execução incremental não pode preparar a empresa inteira');
assert.doesNotMatch(ramoIncremental, /bases\.classificarMovimentos/, 'execução incremental não pode reclassificar a base inteira');
assert.match(api, /A conferência\n\s+\/\/ fiscal canônica ocorre no worker/);
assert.match(fila, /if \(opcoes\.iniciarWorker === true\)/);
assert.doesNotMatch(fila, /iniciarWorker !== false/);
assert.match(fila, /telemetria_reuso_classificacao: resultado\.resumo\.telemetria_reuso_classificacao/, 'o job deve expor somente a telemetria observacional da execução');
const rotaMotor = api.slice(api.indexOf("router.post('/empresas/:id/motor/executar'"), api.indexOf("router.get('/empresas/:id/motor/status'"));
assert.doesNotMatch(rotaMotor, /processamentoCarteira\.executar/);
const rotaProntidaoMotor = api.slice(api.indexOf("router.get('/empresas/:id/motor/prontidao'"), api.indexOf("router.post('/empresas/:id/motor/executar'"));
assert.doesNotMatch(rotaProntidaoMotor, /prepararBaseParaMotor/);
assert.match(rotaProntidaoMotor, /Prontidão exibida para execução do motor/);
const rotaRazao = api.slice(api.indexOf("router.post('/empresas/:id/questor/razao/reclassificar-naturezas'"), api.indexOf("router.post('/empresas/:id/questor/conector/documentos-fiscais-cancelados'"));
assert.match(rotaRazao, /motorExecucaoFila\.solicitarIncremental/);
assert.doesNotMatch(rotaRazao, /motorExecucaoFila\.solicitar\(empresaId,\{\}\)/, 'reaplicação do Razão não pode enfileirar MOTOR_COMPLETO');
assert.match(preparacao, /permitirPublicacao:false/);
assert.match(preparacao, /somenteLeitura:true/);
assert.match(preparacao, /forcar:true/);
assert.match(operacao, /if \(opcoes\.somenteLeitura && divergencia\.bloqueia\)/);
assert.match(operacao, /O motor foi bloqueado/);
console.log('motor-fila-contrato: job deduplicado e consumo exclusivo do worker: OK');
