const assert = require('assert');
const sqlite = require('../src/sqlite');
const pgdas = require('../src/services/pgdasDocumentoIa');

const db = sqlite.abrir(':memory:');
db.exec(`
  CREATE TABLE empresas (id INTEGER PRIMARY KEY, regime TEXT);
  CREATE TABLE perfil_tributario (id INTEGER PRIMARY KEY AUTOINCREMENT, empresa_id INTEGER, competencia TEXT, receita_bruta REAL, receita_recebida REAL, receita_mercadorias REAL, receita_servicos REAL, receita_exportacao REAL, pis REAL, cofins REAL, das REAL, origem TEXT);
  CREATE TABLE pgdas_documentos (id INTEGER PRIMARY KEY AUTOINCREMENT, empresa_id INTEGER, nome_original TEXT, tipo_documento TEXT, mime_type TEXT, conteudo_original BLOB, hash_sha256 TEXT, competencia_detectada TEXT, data_processamento TEXT, metodo_extracao TEXT, status_processamento TEXT);
  CREATE TABLE pgdas_documento_campos (id INTEGER PRIMARY KEY AUTOINCREMENT, documento_id INTEGER, campo TEXT, valor_extraido TEXT, rotulo_original TEXT, pagina_ou_localizacao TEXT, confianca REAL, metodo_extracao TEXT, status_validacao TEXT);
  INSERT INTO empresas VALUES (1, 'simples_nacional'), (2, 'lucro_presumido');
`);

const campos = pgdas.normalizarTexto(`Competência: 02/2026\nReceita Bruta: R$ 12.500,00\nValor DAS: R$ 775,30\nPIS: R$ 12,00`, { localizacoes: [{ texto: 'Valor DAS: R$ 775,30', pagina: 2, confianca: .91 }] });
assert.strictEqual(campos.find((x) => x.campo === 'competencia').valor_extraido, '2026-02');
assert.strictEqual(campos.find((x) => x.campo === 'das').valor_extraido, 775.3);
assert.strictEqual(campos.find((x) => x.campo === 'cofins').valor_extraido, null, 'ausência não pode virar zero');
const tabela = pgdas.normalizarTexto('Receita Bruta Total | R$ 100.000,00\nValor do DAS | R$ 6.500,00\nPIS/Pasep | R$ 100,00\nCofins | R$ 450,00');
assert.strictEqual(tabela.find((x) => x.campo === 'receita_bruta').valor_extraido, 100000);
assert.strictEqual(tabela.find((x) => x.campo === 'das').valor_extraido, 6500);
assert.strictEqual(tabela.find((x) => x.campo === 'pis').valor_extraido, 100);
assert.strictEqual(tabela.find((x) => x.campo === 'cofins').valor_extraido, 450);
const ambigua = pgdas.normalizarTexto(`Receita Bruta do PA (RPA) - Competência | DAS | PIS\n0,00 | 7.000,00 | 100,00\nDocumento completo Receita Bruta DAS PIS Cofins R$ 900.000,00 R$ 0,00`);
assert.strictEqual(ambigua.find((x) => x.campo === 'receita_bruta').valor_extraido, null, 'linha com várias colunas não pode atribuir valor à receita');
const oficial = pgdas.normalizarTexto(`Receita Bruta Auferida (regime competência) | Receita Bruta Recebida (regime caixa) | Valor Total do Débito Declarado (R$)\n112.476,41 | 102.292,29 | 12.850,97\nSublimite de Receita Anual (R$): 3.600.000,00 | Impedido de recolher ICMS/ISS no DAS: Não\nIRPJ | CSLL | COFINS | PIS/Pasep | INSS/CPP | ICMS | IPI | ISS | Total\n558,28 | 462,51 | 1.784,61 | 387,18 | 5.707,32 | 663,49 | 0,00 | 3.287,58 | 12.850,97`);
assert.strictEqual(oficial.find((x) => x.campo === 'receita_bruta').valor_extraido, 112476.41);
assert.strictEqual(oficial.find((x) => x.campo === 'receita_recebida').valor_extraido, 102292.29);
assert.strictEqual(oficial.find((x) => x.campo === 'das').valor_extraido, 12850.97);
assert.strictEqual(oficial.find((x) => x.campo === 'pis').valor_extraido, 387.18);
assert.strictEqual(oficial.find((x) => x.campo === 'cofins').valor_extraido, 1784.61);
const r = pgdas.ingerir(db, 1, { nome_original: 'pgdas.pdf', tipo_documento: 'PDF', mime_type: 'application/pdf', conteudo_original: Buffer.from('pgdas fevereiro'), metodo_extracao: 'prebuilt-layout + NORMALIZACAO' }, campos);
assert.strictEqual(db.prepare('SELECT COUNT(*) c FROM perfil_tributario').get().c, 0, 'OCR pendente nunca entra no histórico antes da confirmação');
assert.strictEqual(pgdas.listar(db, 1)[0].campos_extraidos.length, 9);
const confirmado = pgdas.confirmar(db, 1, r.documento_id);
assert.strictEqual(confirmado.status_processamento, 'VALIDADO_USUARIO');
const perfil = db.prepare('SELECT * FROM perfil_tributario WHERE empresa_id=1').get();
assert.strictEqual(perfil.competencia, '2026-02');
assert.strictEqual(perfil.das, 775.3);
assert.strictEqual(perfil.cofins, null);
assert.throws(() => pgdas.ingerir(db, 2, { nome_original: 'x.pdf', tipo_documento: 'PDF', conteudo_original: Buffer.from('x'), metodo_extracao: 'teste' }, campos), /Simples Nacional/);
db.close();
console.log('PGDAS Azure: leitura determinística, revisão, confirmação e ausência preservada aprovadas.');
