const assert = require('assert');
const fs = require('fs'); const os = require('os'); const path = require('path');
const pasta = fs.mkdtempSync(path.join(os.tmpdir(), 'sattva-planejamento-'));
process.env.SATTVA_DADOS = pasta;
const db = require('../src/db');
const planejamento = require('../src/services/planejamentoTributario');
const a = Number(db.prepare('INSERT INTO empresas (cnpj,razao_social,regime) VALUES (?,?,?)').run('10000000000001','Empresa A','simples_nacional').lastInsertRowid);
const b = Number(db.prepare('INSERT INTO empresas (cnpj,razao_social,regime) VALUES (?,?,?)').run('10000000000002','Empresa B','lucro_presumido').lastInsertRowid);
const estudo = planejamento.criar({ titulo:'Estudo protegido', empresa_ids:[a,b], usuario_id:'usuario-teste', periodo_base_inicio:'2026-01', periodo_base_fim:'2026-12' });
assert.equal(estudo.empresas.length, 2);
assert.equal(estudo.snapshot.versao, 1);
const solicitacoes = estudo.snapshot.dados.necessidades_coleta.flatMap((x) => x.itens.map((i) => i.titulo));
assert.ok(solicitacoes.some((x) => /PGDAS 2025/.test(x)));
assert.ok(solicitacoes.some((x) => /PGDAS 2024/.test(x)));
assert.ok(!solicitacoes.some((x) => /Folha|pró-labore/i.test(x)));
assert.equal(db.prepare('SELECT COUNT(*) c FROM planejamento_snapshots WHERE analise_id=?').get(estudo.analise.id).c, 1);
const premissa = planejamento.adicionarPremissa(estudo.analise.id, { campo:'crescimento_receita', valor:'0.1', origem:'PREMISSA_MANUAL' }, 'usuario-teste');
assert.ok(premissa > 0);
const execucao = planejamento.executar(estudo.analise.id, 'usuario-teste');
assert.equal(execucao.resultados.length, 5);
assert.equal(db.prepare('SELECT COUNT(*) c FROM planejamento_resultados WHERE analise_id=?').get(estudo.analise.id).c, 5);
assert.ok(db.prepare("SELECT COUNT(*) c FROM planejamento_eventos WHERE analise_id=? AND acao='snapshot_created'").get(estudo.analise.id).c === 1);
assert.equal(db.prepare('SELECT regime FROM empresas WHERE id=?').get(a).regime, 'simples_nacional');
planejamento.aprovar(estudo.analise.id, 'Revisão humana registrada.', 'usuario-teste');
assert.equal(planejamento.obter(estudo.analise.id).analise.status, 'APROVADA');
db.close();
fs.rmSync(pasta, { recursive:true, force:true });
console.log('planejamento-tributario.test.js: OK');
