const { resolverFato, criarPendencia } = require('./cadastroFiscalComplementar');
const db = require('../db');
const { catalogoResolvido } = require('./tratamentoPisCofins');
const vig=(r,d)=>(!r.vigencia_inicio||r.vigencia_inicio<=d)&&(!r.vigencia_fim||r.vigencia_fim>=d);
function comparar(valor, operador, esperado){if(operador==='VERDADEIRO')return valor===true;if(operador==='FALSO')return valor===false;if(operador==='IGUAL')return valor===esperado;if(operador==='DIFERENTE')return valor!==esperado;if(operador==='EM')return Array.isArray(esperado)&&esperado.includes(valor);if(operador==='NAO_EM')return Array.isArray(esperado)&&!esperado.includes(valor);throw new Error('Operador condicional inválido.');}
function avaliarCondicoes(regra, contexto){const condicoes=Array.isArray(regra.condicoes)?regra.condicoes:JSON.parse(regra.condicoes||'[]');const fatos=[];for(const c of condicoes){const f=resolverFato(contexto,c.fato);fatos.push(f);if(['NAO_DETERMINADO','CONFLITO_DE_FATO'].includes(f.status))return {status:'INDETERMINADA',motivo:'CONDICAO_NAO_COMPROVADA',fato_faltante:c.fato,fatos};if(!comparar(f.valor,c.operador,c.valor))return {status:'NAO_APLICAVEL',fatos};}return {status:'APLICAVEL',fatos};}
function selecionar(regras,contexto,{criar_pendencia=false}={}){const d=String(contexto.data_operacao||contexto.data||new Date().toISOString().slice(0,10)).slice(0,10);const regime=contexto.regime_pis_cofins||({lucro_presumido:'CUMULATIVO',lucro_real:'NAO_CUMULATIVO'}[contexto.regime]||'');const avaliadas=regras.filter(r=>vig(r,d)&&(!r.regime_pis_cofins||r.regime_pis_cofins===regime)).map(r=>({regra:r,avaliacao:avaliarCondicoes(r,contexto)}));const aplicaveis=avaliadas.filter(x=>x.avaliacao.status==='APLICAVEL').sort((a,b)=>(b.regra.prioridade||0)-(a.regra.prioridade||0));if(aplicaveis.length>1&&(aplicaveis[0].regra.prioridade||0)===(aplicaveis[1].regra.prioridade||0)&&JSON.stringify(aplicaveis[0].regra.resultado)!==JSON.stringify(aplicaveis[1].regra.resultado))return {status:'CONFLITO_REGRAS',avaliadas};if(aplicaveis[0])return {status:'APLICAVEL',selecionada:aplicaveis[0],avaliadas};const ind=avaliadas.find(x=>x.avaliacao.status==='INDETERMINADA');if(ind&&criar_pendencia&&contexto.empresa_id&&(contexto.produto_empresa_id||contexto.codigo_produto))criarPendencia({empresa_id:contexto.empresa_id,produto_empresa_id:contexto.produto_empresa_id||null,codigo_produto:contexto.codigo_produto||null,ncm:contexto.ncm,regra_id:ind.regra.regra_id,regra_candidata:ind.regra.regra_id,familia_regra:ind.regra.familia_regra,fato_faltante:ind.avaliacao.fato_faltante});return {status:ind?'INDETERMINADA':'NAO_APLICAVEL',avaliadas};}
function sombra({oficial,regras,contexto,criar_pendencia=false}){const r=selecionar(regras,contexto,{criar_pendencia});return {resultado_oficial:oficial,resultado_condicional_sombra:r.status==='APLICAVEL'?r.selecionada.regra.resultado:oficial,avaliacao:r,gravou_producao:false};}
function regrasCandidatas(movimento){const ncm=String(movimento.ncm||'').trim(),nbs=String(movimento.nbs||'').trim(),lc116=String(movimento.lc116||'').replace(/\D/g,'').padStart(4,'0').slice(0,4);let linhas=[];if(ncm)linhas=db.prepare("SELECT * FROM regras_enquadramento WHERE status='ATIVA' AND ncm=? ORDER BY prioridade DESC, versao DESC, id").all(ncm);else if(nbs)linhas=db.prepare("SELECT * FROM regras_enquadramento WHERE status='ATIVA' AND nbs=? AND (lc116 IS NULL OR lc116='' OR lc116=?) ORDER BY CASE WHEN lc116=? THEN 1 ELSE 0 END DESC, prioridade DESC, versao DESC, id").all(nbs,lc116,lc116);return linhas.map(r=>({regra_id:r.id,familia_regra:r.familia,prioridade:r.prioridade,vigencia_inicio:r.vigencia_inicio,vigencia_fim:r.vigencia_fim,regime_pis_cofins:r.regime_pis_cofins,condicoes:JSON.parse(r.condicoes_obrigatorias||'[]'),resultado:{tratamento:r.tratamento_resultante||null,cst_pis:r.cst_pis,cst_cofins:r.cst_cofins,pis:r.pis_percentual,cofins:r.cofins_percentual}}));}
function resolverTratamentoAtivo(movimento, contexto = {}) {
  const regras = regrasCandidatas(movimento);
  const avaliacao = selecionar(regras, { empresa_id: movimento.empresa_id, produto_empresa_id: movimento.produto_empresa_id || null,
    codigo_produto: movimento.codigo_produto, ncm: movimento.ncm, regime: contexto.regime || movimento.regime,
    regime_pis_cofins: contexto.regime_pis_cofins, data_operacao: movimento.data_emissao || movimento.competencia,
    movimento_id: movimento.id, fatos_operacao: contexto.fatos_operacao, fatos_documento: contexto.fatos_documento,
    fatos_cfop: contexto.fatos_cfop, fatos_produto: contexto.fatos_produto, fatos_empresa: contexto.fatos_empresa });
  if (avaliacao.status !== 'APLICAVEL') return { status: avaliacao.status, avaliacao, regra: avaliacao.avaliadas?.[0]?.regra || null, catalogo_fiscal: null };
  const regra = avaliacao.selecionada.regra;
  return { status: 'APLICAVEL', avaliacao, regra, catalogo_fiscal: catalogoResolvido(regra.resultado.tratamento, regra.regra_id) };
}
function executarSombraAposOficial({movimento,resultado_oficial,regras}) { if(process.env.PIS_COFINS_CONDICIONAL_SHADOW!=='true') return {executada:false,motivo:'FEATURE_FLAG_DESLIGADA'}; const contexto={empresa_id:movimento.empresa_id,produto_empresa_id:movimento.produto_empresa_id||null,codigo_produto:movimento.codigo_produto,ncm:movimento.ncm,cfop:movimento.cfop,regime:movimento.regime,regime_pis_cofins:movimento.regime_pis_cofins,data_operacao:movimento.data_emissao||movimento.competencia,movimento_id:movimento.id}; const candidatas=regras||regrasCandidatas(movimento); const r=sombra({oficial:resultado_oficial,regras:candidatas,contexto,criar_pendencia:true}); db.prepare('INSERT INTO motor_condicional_sombra (movimento_id,empresa_id,produto_empresa_id,ncm,regra_candidata,regra_selecionada,familia_regra,condicoes,fatos_resolvidos,status_avaliacao,resultado_oficial,resultado_sombra,diferenca,motivo) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(movimento.id||null,movimento.empresa_id,contexto.produto_empresa_id,movimento.ncm||null,r.avaliacao.avaliadas?.[0]?.regra?.regra_id||null,r.avaliacao.selecionada?.regra?.regra_id||null,r.avaliacao.selecionada?.regra?.familia_regra||null,JSON.stringify(r.avaliacao.avaliadas||[]),JSON.stringify(r.avaliacao.selecionada?.avaliacao?.fatos||[]),r.avaliacao.status,JSON.stringify(resultado_oficial),JSON.stringify(r.resultado_condicional_sombra),JSON.stringify({}),r.avaliacao.motivo||null); return {...r,executada:true}; }
module.exports={avaliarCondicoes,selecionar,sombra,regrasCandidatas,resolverTratamentoAtivo,executarSombraAposOficial};
