/* Auditoria sombra: não escreve motor, movimentos nem catálogos. */
const path=require('path'); require('dotenv').config({path:path.join(__dirname,'..','.env'),quiet:true}); const {Client}=require('pg');
const {construirAssinaturaCBS,compararAssinaturasCBS}=require('../src/services/assinaturaTributariaCBS');
(async()=>{const c=new Client({connectionString:process.env.SUPABASE_DB_URL,ssl:{rejectUnauthorized:false}});await c.connect();try{
 const base=await c.query(`select b.id,b.lc116,b.nbs,b.cclasstrib,b.catalogo_linha_id,c.codigo cclass_codigo,c.pred_cbs,c.tipo_aliquota,c.ind_gtrib_regular,c.ind_gcred_pres_op,c.ind_gmono_padrao,c.ind_gmono_reten,c.ind_gmono_ret,c.ind_gmono_dif,c.ind_gestorno_cred,s.codigo cst_codigo,s.ind_gred,s.ind_gdif,s.ind_gibs_cbs_mono,s.ind_gtransf_cred,s.ind_redutor_bc from public.base_servicos b left join public.catalogo_cclasstrib c on c.codigo=trim(b.cclasstrib) and c.catalogo_versao_id=(select id from public.catalogo_versoes where dominio='CCLASSTRIB_IBS_CBS' and versao='2026-06-22') left join public.catalogo_cst s on s.codigo=c.cst_codigo_origem and s.catalogo_versao_id=(select id from public.catalogo_versoes where dominio='CST_IBS_CBS' and versao='2026-06-22')`);
 const assinaturas=base.rows.filter(r=>r.catalogo_linha_id && r.cclass_codigo && r.cst_codigo).map(r=>({id:r.id,lc116:r.lc116,assinatura:construirAssinaturaCBS({codigo:r.cst_codigo,...r},{codigo:r.cclass_codigo,...r})}));
 const grupos=['0105','0107','1401','1702'].map(lc=>{const xs=assinaturas.filter(x=>String(x.lc116||'').replace(/\D/g,'').padStart(4,'0').slice(0,4)===lc); return {lc116:lc,candidatos_com_assinatura:xs.length,resultado:xs.length?compararAssinaturasCBS(xs.map(x=>x.assinatura)):'INDETERMINADO_SEM_CCLASSTRIB'};});
 const exec=await c.query(`select count(*)::int resultados,coalesce(sum((dados->>'cbs')::numeric),0)::text cbs from public.motor_resultados_operacionais where empresa_id=1 and execucao_id=14 and ativo=true`);
 const out={catalogo:{cst:18,cclasstrib:164,relacoes:164},base_servicos:{total:base.rows.length,com_linhagem:base.rows.filter(r=>r.catalogo_linha_id).length,sem_cclasstrib:base.rows.filter(r=>r.catalogo_linha_id&&!r.cclass_codigo).length,assinaturas_cbs:assinaturas.length},grupos,pendencias_servico:{sem_nbs:41,requer_validacao:44},baseline:exec.rows[0]};console.log(JSON.stringify(out,null,2));
 }finally{await c.end()}})().catch(e=>{console.error(e.stack||e.message);process.exit(1)});
