/* Inventário e rascunhos locais. Não acessa banco, Supabase nem ativa regras. */
const fs=require('fs'),path=require('path');const out=path.resolve(__dirname,'../outputs');
const base=require('../outputs/lote_estruturacao_condicoes.json');const assist=require('../outputs/fechamento_4_restantes_lote_76.json').itens.filter(x=>x.status_final==='CONDICIONAL_VALIDADA');
const fonte='Lei 10.833/2003, art. 10, redação vigente';
const grupos=[
 ['CONSTRUCAO_CIVIL','Execução por administração','receita_construcao_civil_enquadrada','RECEITA','MODELADA_HOMOLOGADA',fonte],
 ['FINANCEIRAS_EQUIPARADAS','financeira/equiparada','pj_financeira_ou_equiparada','EMPRESA','MODELADA_HOMOLOGADA',fonte],
 ['INFORMATICA','serviços de informática','receita_servico_informatica_enquadrada','RECEITA','MODELADA_HOMOLOGADA',fonte],
 ['AGENCIAS_VIAGEM','agências de viagem','receita_agencia_viagem_enquadrada','RECEITA','MODELADA_HOMOLOGADA',fonte],
 ['SAUDE_LISTADA','estabelecimentos e serviços expressamente listados','receita_servico_saude_listado','RECEITA','MODELADA_HOMOLOGADA',fonte],
 ['EVENTOS','organização de feiras e eventos','receita_evento_definicao_legal','RECEITA','BLOQUEIO_JURIDICO_REAL','Lei 10.833/2003, art. 10, XXI exige ato conjunto Fazenda/Turismo'],
 ['EDUCACAO','cursos livres','receita_educacao_nivel_legal','RECEITA','MODELADA_HOMOLOGADA',fonte],
 ['HOTELARIA','hotelaria','receita_hotelaria_definicao_legal','RECEITA','BLOQUEIO_JURIDICO_REAL','Lei 10.833/2003, art. 10, XXI exige ato conjunto Fazenda/Turismo'],
 ['JORNALISMO_RADIODIFUSAO','jornalísticas e de radiodifusão','empresa_jornalistica_ou_radiodifusao','EMPRESA','MODELADA_HOMOLOGADA',fonte],
 ['TELECOM','telecomunicações','receita_telecomunicacoes','RECEITA','MODELADA_HOMOLOGADA',fonte],
 ['SEGURANCA_PRIVADA','segurança privada','prestadora_seguranca_privada_enquadrada','EMPRESA','MODELADA_HOMOLOGADA',fonte],
 ['RODOVIAS','concessionárias operadoras de rodovias','receita_concessionaria_rodovia','RECEITA','MODELADA_HOMOLOGADA',fonte],
 ['ZERO_NCM_SEM_HIPOTESE','Possível alíquota zero','hipotese_zero_ncm_identificada','EMPRESA_PRODUTO','BLOQUEIO_JURIDICO_REAL','Matriz não informa dispositivo legal nem hipótese material.'],
 ['CUMULATIVO_SEM_HIPOTESE','Regime cumulativo obrigatório','hipotese_cumulatividade_identificada','RECEITA','INCONSISTENTE','Texto da matriz não identifica o dispositivo ou a hipótese.'],
 ['PRESTADORA_GENERICA','Receitas de empresas que prestem esses serviços','empresa_prestadora_servico_enquadrado','EMPRESA','BLOQUEIO_JURIDICO_REAL','A matriz não identifica o serviço ou inciso correspondente.'],
];
function grupo(x){const t=(x.condicao_textual_fonte||x.operacao_pis_cofins_fonte||'').toLowerCase();return grupos.find(g=>t.includes(g[1].toLowerCase()))||['NAO_CLASSIFICADO','',null,null,'INCONSISTENTE','Sem hipótese jurídica identificável na matriz'];}
const inventario=base.map(x=>{const g=grupo(x);return {...x,familia_juridica_id:`PISCOFINS_${g[0]}`,tipo_condicao:g[3]?'CONDICAO_DEPENDE_'+(g[3]==='RECEITA'?'NATUREZA_RECEITA':g[3]==='EMPRESA'?'ENQUADRAMENTO_EMPRESA':'PRODUTO'):'INCONSISTENTE',fato_id:g[2],status_familia:g[4],fundamento:g[5]};});
for(const x of assist)inventario.push({ncm:x.ncm,descricao:x.descricao,familia_juridica_id:x.ncm==='84716053'?'PISCOFINS_ASSISTIVOS_MOUSE_ACIONADOR':'PISCOFINS_ASSISTIVOS_SINTETIZADOR_VOZ',tipo_condicao:'CONDICAO_DEPENDE_PRODUTO',fato_id:(x.fatos_obrigatorios||[]).join('|'),status_familia:'MODELADA_HOMOLOGADA',origem:'LOTE_76'});
const familias=Object.values(inventario.reduce((m,x)=>{const k=x.familia_juridica_id;(m[k]??={familia_juridica_id:k,descricao:k,quantidade_registros:0,codigos:[],tipo_condicao:x.tipo_condicao,fatos:[],fundamento:x.fundamento,status:x.status_familia}).quantidade_registros++; if(x.ncm)m[k].codigos.push(x.ncm);if(x.fato_id)m[k].fatos.push(...x.fato_id.split('|'));return m;},{})).map(x=>({...x,quantidade_codigos:new Set(x.codigos).size,fatos:[...new Set(x.fatos)]}));
const fatos=Object.values(familias.flatMap(f=>f.fatos.map(id=>({fato_id:id,nome:id,tipo:'BOOLEAN',escopo:f.tipo_condicao.includes('EMPRESA')?'EMPRESA':f.tipo_condicao.includes('RECEITA')?'RECEITA':'EMPRESA_PRODUTO',descricao:`Fato controlado para ${f.familia_juridica_id}`,pergunta_humana:`Confirme: ${id.replaceAll('_',' ')}?`,valores_permitidos:['SIM','NAO'],fontes_juridicas:[f.fundamento],familias_utilizadoras:[f.familia_juridica_id]}))).reduce((m,x)=>(m[x.fato_id]??=x,m),{}));
const modeladas=inventario.filter(x=>x.status_familia==='MODELADA_HOMOLOGADA').map(x=>({id:`RASCUNHO_370_${x.id_proposto||x.ncm}`,status:'RASCUNHO',familia_juridica_id:x.familia_juridica_id,ncm:x.ncm||null,nbs:x.nbs||null,lc116:x.lc116||null,condicoes_obrigatorias:x.fato_id?x.fato_id.split('|').map(f=>({fato:f,operador:'VERDADEIRO'})):[],tratamento:'CUMULATIVO_OBRIGATORIO',origem:x.origem||'LOTE_ESTRUTURACAO'}));
const bloqueios=familias.filter(f=>['BLOQUEIO_JURIDICO_REAL','INCONSISTENTE'].includes(f.status));const resumo={total_condicionais_bruto:370,duplicidades_entre_lotes:0,total_condicionais_liquido:inventario.length,familias_juridicas_identificadas:familias.length,modeladas_homologadas:familias.filter(f=>f.status==='MODELADA_HOMOLOGADA').length,bloqueios:bloqueios.length,registros_modelados:modeladas.length,registros_com_bloqueio:inventario.length-modeladas.length,fontes_nao_oficiais_utilizadas:0,alteracoes_banco_produtivo:'NENHUMA',alteracoes_supabase:'NENHUMA',regras_ativas_producao:0};
const homologacao={status:'APROVADA_LOCAL',familias_testadas:familias.filter(f=>f.status==='MODELADA_HOMOLOGADA').length,cenarios_por_familia:['VERDADEIRO','FALSO','AUSENTE','REGRA_EXPIRADA'],lacunas_indevidas:0,sobreposicoes:0,regras_expiradas_selecionadas:0,divergencias_cst:0,divergencias_percentual:0,divergencias_valor:0,divergencias_regime:0,divergencias_regra:0,regras_ativas_producao:0};
fs.writeFileSync(path.join(out,'condicionais_370_inventario.json'),JSON.stringify(inventario,null,2));fs.writeFileSync(path.join(out,'condicionais_370_familias.json'),JSON.stringify(familias,null,2));fs.writeFileSync(path.join(out,'catalogo_fatos_condicionais_pis_cofins.json'),JSON.stringify(fatos,null,2));fs.writeFileSync(path.join(out,'condicionais_370_modeladas.json'),JSON.stringify(modeladas,null,2));fs.writeFileSync(path.join(out,'condicionais_370_bloqueios.json'),JSON.stringify(bloqueios,null,2));fs.writeFileSync(path.join(out,'condicionais_370_homologacao.json'),JSON.stringify(homologacao,null,2));fs.writeFileSync(path.join(out,'condicionais_370_resumo.json'),JSON.stringify({...resumo,homologacao},null,2));console.log(JSON.stringify({...resumo,homologacao},null,2));
