/* Fechamento local dos quatro assistivos. Não acessa banco ou Supabase. */
const fs=require('fs'),path=require('path'); const out=path.resolve(__dirname,'../outputs');
const fontes=['https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2004/lei/l10.865compilado.htm','https://www.gov.br/planejamento/pt-br/assuntos/orcamento/orcamentos-anuais/2026/loa/lei-orcamentaria-anual-2026','https://www.gov.br/planejamento/pt-br/assuntos/orcamento/orcamentos-anuais/2026/loa/comparativo-ploa-2026-x-loa-2026.pdf','https://www.gov.br/planejamento/pt-br/assuntos/orcamento/orcamentos-anuais/2026/ploa/01_ics_ploa_2026_volume_i-web.pdf','https://www.gov.br/receitafederal/pt-br/centrais-de-conteudo/publicacoes/relatorios/renuncia/gastos-tributarios-bases-efetivas/sistema-tributario-de-referencia-str-v1-02.pdf','https://www2.camara.leg.br/legin/fed/leicom/2025/leicomplementar-224-26-dezembro-2025-798608-normaatualizada-pl.html'];
const itens=[
 ['84701000','Calculadora com sintetizador de voz','XXV','possui_sintetizador_voz'],
 ['84716053','Mouse adaptado ou acionador de pressão','XXVII e XXXI',['adaptado_para_pessoa_com_deficiencia','acionador_pressao']],
 ['84719014','Scanner com sintetizador de voz','XXIX','possui_sintetizador_voz'],
 ['87142000','Partes e acessórios de cadeiras de rodas','XXIV',null]
];
function regra(ncm,nome,inciso,fato,regime='TODOS',inicio=null,fim=null){return {id:`RASCUNHO_ASSISTIVO_${ncm}_${inciso.replaceAll(' ','_')}_${fato||'DIRETA'}_${regime}`,status:'RASCUNHO',familia:'FAMILIA_LEI_10865_ART28_ASSISTIVOS',tipo_chave:'NCM',ncm,condicoes_obrigatorias:fato?[{fato,operador:'VERDADEIRO'}]:[],regime_pis_cofins:regime==='TODOS'?null:regime,cst_pis:'06',cst_cofins:'06',pis_percentual:inicio==='2026-04-01'?(regime==='CUMULATIVO'?0.065:0.165):0,cofins_percentual:inicio==='2026-04-01'?(regime==='CUMULATIVO'?0.30:0.76):0,tratamento_resultante:inicio==='2026-04-01'?'BENEFICIO_REDUZIDO_LC224':'ALIQUOTA_ZERO_PIS_COFINS',vigencia_inicio:inicio,vigencia_fim:fim,prioridade_proposta:50,versao_proposta:inicio==='2026-04-01'?2:1,fundamento_legal:{lei:'Lei 10.865/2004',artigo:'28',inciso,lc224:'LC 224/2025, art. 4º, §2º, I; categoria DGT 2026 Cadeira de Rodas e Aparelhos Assistivos; sem exceção do §8º aplicável.'},fontes_oficiais:fontes};}
const r=[];for(const [n,d,i,f] of itens){const fatos=Array.isArray(f)?f:[f];for(const x of fatos){const inciso=x==='adaptado_para_pessoa_com_deficiencia'?'XXVII':x==='acionador_pressao'?'XXXI':i;r.push(regra(n,d,inciso,x,'TODOS',null,'2026-03-31'),regra(n,d,inciso,x,'CUMULATIVO','2026-04-01'),regra(n,d,inciso,x,'NAO_CUMULATIVO','2026-04-01'));}}
const cond=r.filter(x=>x.condicoes_obrigatorias.length),direta=r.filter(x=>!x.condicoes_obrigatorias.length);const fechamento={dgt_loa2026_comprovado:'SIM',evidencia_dgt:['PLOA 2026, Informações Complementares, Quadro III: Cadeira de Rodas e Aparelhos Assistivos','RFB STR: Lei 10.865/2004, arts. 8º e 28, com calculadoras, mouse, scanners, acionadores e 8714.20.00','LC 224/2025, art. 4º, §2º, I: benefícios no DGT de 2026; §8º sem exceção aplicável à categoria'],alteracao_ploa_loa_afetou_beneficio:'NAO',lc224:Object.fromEntries(itens.map(([n])=>[n,'ALCANCADO'])),itens:itens.map(([n,d,i,f])=>({ncm:n,descricao:d,fundamento_original:`Lei 10.865/2004, art. 28, inciso ${i}`,requisito_material:f||'NCM suficiente',fatos_obrigatorios:Array.isArray(f)?f:f?[f]:[],impacto_lc224:'ALCANCADO',status_final:f?'CONDICIONAL_VALIDADA':'DIRETA_VALIDADA',fontes_oficiais:fontes})),regras:r,condicionais_modeladas:3,regras_tecnicas_condicionais:cond.length,diretas_modeladas:1,regras_tecnicas_diretas:direta.length,regras_ativas_producao:0,alteracoes_banco_produtivo:'NENHUMA',alteracoes_supabase:'NENHUMA'};
fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'fechamento_4_restantes_lote_76.json'),JSON.stringify(fechamento,null,2));fs.writeFileSync(path.join(out,'regras_condicionais_3_assistivos.json'),JSON.stringify(cond,null,2));fs.writeFileSync(path.join(out,'regra_direta_87142000.json'),JSON.stringify(direta,null,2));fs.writeFileSync(path.join(out,'fechamento_4_restantes_lote_76_resumo.json'),JSON.stringify({...fechamento,regras:undefined},null,2));
const anterior=JSON.parse(fs.readFileSync(path.join(out,'mapeamento_legal_76_diretas.json'),'utf8')); const anteriores=(anterior.registros||anterior.regras||anterior.itens||[]).filter(x=>!itens.some(([n])=>n===String(x.ncm||x.chave||''))).map(x=>({ncm:String(x.ncm||x.chave||''),status_final:'VALIDADA_LOTE_72'})).filter(x=>x.ncm); const finais=[...anteriores,...fechamento.itens.map(x=>({ncm:x.ncm,status_final:x.status_final}))]; fs.writeFileSync(path.join(out,'lote_76_status_final.json'),JSON.stringify({registros_lote_original:76,registros_fechados:finais.length,lote_original_76_fechado:finais.length===76?'SIM':'NAO',itens:finais},null,2));
console.log(JSON.stringify({regras:r.length,condicionais:cond.length,diretas:direta.length,lote:finais.length},null,2));
