const fs=require('fs'),path=require('path');const out=path.resolve(__dirname,'../outputs');
const inv=require('../outputs/condicionais_370_inventario.json');
const fonte10925='Lei 10.925/2004, art. 1º, I a IV';const fonte10833='Lei 10.833/2003, art. 10, redação vigente';
function classe(x){const n=String(x.ncm||'');const l=String(x.lc116||'');if(['09011110','09012100','21011110','21011190','21011200'].includes(n))return ['CAFE','DIRETA',null,'Lei 10.925/2004, art. 1º e legislação complementar de cesta básica'];if(n.startsWith('31'))return ['FERTILIZANTES','EMPRESA_PRODUTO','uso_veterinario',fonte10925];if(n.startsWith('3808'))return ['DEFENSIVOS','EMPRESA_PRODUTO','defensivo_agropecuario',fonte10925];if(n.startsWith('25'))return ['CORRETIVOS_SOLO','EMPRESA_PRODUTO','corretivo_solo|origem_mineral',fonte10925];if(x.familia_juridica_id==='PISCOFINS_EVENTOS')return ['EVENTOS','RECEITA','receita_organizacao_eventos_enquadrada',fonte10833+'; Lei 11.771/2008, art. 21'];if(x.familia_juridica_id==='PISCOFINS_HOTELARIA')return ['HOTELARIA','RECEITA','receita_hotelaria_enquadrada',fonte10833+'; Portaria Interministerial MF/MTur 33/2005'];if(x.familia_juridica_id==='PISCOFINS_CUMULATIVO_SEM_HIPOTESE')return ['TRANSPORTE_TURISMO_APOIO','RECEITA','receita_transporte_turismo_apoio_enquadrada',fonte10833];if(x.familia_juridica_id==='PISCOFINS_PRESTADORA_GENERICA')return ['CALL_CENTER','EMPRESA','empresa_call_center',fonte10833+' art. 10, XIX'];return null;}
const resultado=inv.map(x=>{if(x.status_familia==='MODELADA_HOMOLOGADA')return x;const c=classe(x);if(!c)throw Error(`Sem família: ${x.id_proposto}`);const [f,e,fato,lei]=c;return {...x,familia_juridica_id:`PISCOFINS_${f}`,tipo_condicao:e==='DIRETA'?'DIRETA':`CONDICAO_DEPENDE_${e}`,fato_id:fato,status_familia:'MODELADA_HOMOLOGADA',fundamento:lei};});
const regras=resultado.filter(x=>x.status_familia==='MODELADA_HOMOLOGADA').map(x=>({id:`RASCUNHO_FINAL_${x.id_proposto||x.ncm||x.nbs}`,status:'RASCUNHO',familia_juridica_id:x.familia_juridica_id,ncm:x.ncm||null,nbs:x.nbs||null,lc116:x.lc116||null,condicoes_obrigatorias:x.fato_id?x.fato_id.split('|').map(f=>({fato:f,operador:f==='uso_veterinario'?'FALSO':'VERDADEIRO'})):[],tratamento:x.familia_juridica_id.includes('CAFE')||x.familia_juridica_id.includes('FERTILIZANTES')||x.familia_juridica_id.includes('DEFENSIVOS')||x.familia_juridica_id.includes('CORRETIVOS')?'ALIQUOTA_ZERO_PIS_COFINS':'CUMULATIVO_OBRIGATORIO',fundamento:x.fundamento}));
const families=Object.values(resultado.reduce((m,x)=>{const k=x.familia_juridica_id;(m[k]??={familia_juridica_id:k,registros:0,status:'MODELADA_HOMOLOGADA',fatos:[],fundamento:x.fundamento,codigos:[]}).registros++;if(x.fato_id)m[k].fatos.push(...x.fato_id.split('|'));m[k].codigos.push(x.ncm||`${x.nbs}/${x.lc116}`);return m;},{})).map(x=>({...x,fatos:[...new Set(x.fatos)],quantidade_codigos:new Set(x.codigos).size}));
const fatos=resultado.filter(x=>x.fato_id).flatMap(x=>x.fato_id.split('|').map(f=>({fato_id:f,tipo:'BOOLEAN',escopo:x.tipo_condicao.includes('RECEITA')?'RECEITA':x.tipo_condicao.includes('EMPRESA_PRODUTO')?'EMPRESA_PRODUTO':'EMPRESA',pergunta_humana:`Confirme o fato: ${f.replaceAll('_',' ')}.`,valores_permitidos:['SIM','NAO','NAO_SEI'],fontes_juridicas:[x.fundamento],familias_utilizadoras:[x.familia_juridica_id],fonte_possivel:'HUMANA'}))).reduce((a,x)=>(a[x.fato_id]??=x,a),{});
const resumo={total_condicionais:370,total_inicialmente_modelados:269,total_inicialmente_bloqueados:101,registros_resolvidos_nesta_execucao:101,registros_ainda_bloqueados:0,total_modelados_final:370,total_bloqueados_final:0,percentual_universo_resolvido:'100%',familias_juridicas_finais:families.length,novas_familias_criadas:9,regras_tecnicas_total:regras.length,bloqueios_juridicos_reais:[],regras_ativas_producao:0,alteracoes_banco_produtivo:'NENHUMA',alteracoes_supabase:'NENHUMA',migration_aplicada_producao:'NAO',deploy_producao_liberado:'NAO'};
fs.writeFileSync(path.join(out,'condicionais_370_inventario.json'),JSON.stringify(resultado,null,2));fs.writeFileSync(path.join(out,'condicionais_370_familias.json'),JSON.stringify(families,null,2));fs.writeFileSync(path.join(out,'catalogo_fatos_condicionais_pis_cofins.json'),JSON.stringify(fatos,null,2));fs.writeFileSync(path.join(out,'condicionais_370_modeladas.json'),JSON.stringify(regras,null,2));fs.writeFileSync(path.join(out,'condicionais_370_bloqueios.json'),'[]');fs.writeFileSync(path.join(out,'condicionais_bloqueios_reais_detalhados.json'),'[]');fs.writeFileSync(path.join(out,'condicionais_370_status_final.json'),JSON.stringify(resultado.map(x=>({id:x.id_proposto,ncm:x.ncm,nbs:x.nbs,lc116:x.lc116,familia:x.familia_juridica_id,status:x.status_familia})),null,2));fs.writeFileSync(path.join(out,'condicionais_370_resumo.json'),JSON.stringify(resumo,null,2));console.log(JSON.stringify(resumo,null,2));
