/* Cria a trilha durável do PGDAS no Supabase. Pode ser executado repetidamente. */
require('dotenv').config();
const { Client } = require('pg');

const SQL = `
CREATE TABLE IF NOT EXISTS public.pgdas_documentos (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  origem_local_id bigint,
  nome_original text not null,
  tipo_documento text not null,
  mime_type text,
  conteudo_original bytea not null,
  hash_sha256 text not null,
  competencia_detectada text,
  data_processamento text not null,
  metodo_extracao text not null,
  status_processamento text not null,
  criado_em text default now()::text,
  unique (empresa_id, hash_sha256),
  unique (empresa_id, origem_local_id)
);
CREATE INDEX IF NOT EXISTS ix_pgdas_documentos_empresa_competencia_remoto ON public.pgdas_documentos (empresa_id, competencia_detectada desc);
CREATE TABLE IF NOT EXISTS public.pgdas_documento_campos (
  id bigint generated by default as identity primary key,
  documento_id bigint not null references public.pgdas_documentos(id) on delete cascade,
  campo text not null,
  valor_extraido text,
  rotulo_original text,
  pagina_ou_localizacao text,
  confianca numeric,
  metodo_extracao text,
  status_validacao text,
  unique (documento_id, campo)
);
`;

async function executar() {
  const client = new Client({ connectionString: process.env.SUPABASE_DB_URL, ssl: { rejectUnauthorized: false } });
  await client.connect();
  try { await client.query(SQL); console.log('PGDAS durável: schema Supabase pronto.'); }
  finally { await client.end(); }
}
if (require.main === module) executar().catch((e) => { console.error(`ERRO: ${e.message}`); process.exitCode = 1; });
module.exports = { executar };
