-- Camada aditiva de evidência histórica. Não altera movimentos, motor ou CBS.
create table if not exists public.pis_cofins_apuracao_documentos (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  nome_original text not null,
  tipo_documento text not null check (tipo_documento in ('PDF','XLSX','CSV','RELATORIO_ERP')),
  mime_type text,
  conteudo_original bytea not null,
  hash_sha256 text not null,
  competencia_detectada text,
  data_processamento timestamptz not null default now(),
  versao_modelo_extracao text not null,
  status_processamento text not null,
  criado_em timestamptz not null default now(),
  unique (empresa_id, hash_sha256)
);
create index if not exists ix_apuracao_documentos_empresa_competencia
  on public.pis_cofins_apuracao_documentos(empresa_id, competencia_detectada desc);

create table if not exists public.pis_cofins_apuracoes_historicas (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  documento_id bigint not null unique references public.pis_cofins_apuracao_documentos(id) on delete cascade,
  competencia text,
  regime_pis_cofins text,
  receita_base numeric,
  pis_debito numeric, cofins_debito numeric,
  pis_credito numeric, cofins_credito numeric,
  pis_credito_utilizado numeric, cofins_credito_utilizado numeric,
  saldo_pis numeric, saldo_cofins numeric,
  pis_recolhido numeric, cofins_recolhida numeric,
  observacoes text,
  status_validacao text not null check (status_validacao in ('VALIDADO_AUTOMATICAMENTE','REQUER_VALIDACAO','VALIDADO_USUARIO','INDETERMINADO')),
  divergencias jsonb,
  criado_em timestamptz not null default now()
);
create index if not exists ix_apuracoes_historicas_empresa_competencia
  on public.pis_cofins_apuracoes_historicas(empresa_id, competencia desc);

create table if not exists public.pis_cofins_apuracao_campos (
  id bigint generated by default as identity primary key,
  apuracao_id bigint not null references public.pis_cofins_apuracoes_historicas(id) on delete cascade,
  campo text not null,
  valor_extraido text,
  origem_documento text,
  pagina_ou_localizacao text,
  rotulo_original text,
  confianca numeric check (confianca is null or (confianca >= 0 and confianca <= 1)),
  metodo_extracao text not null,
  status_validacao text not null check (status_validacao in ('VALIDADO_AUTOMATICAMENTE','REQUER_VALIDACAO','VALIDADO_USUARIO','INDETERMINADO')),
  criado_em timestamptz not null default now(),
  unique (apuracao_id, campo)
);

alter table public.pis_cofins_apuracao_documentos enable row level security;
alter table public.pis_cofins_apuracoes_historicas enable row level security;
alter table public.pis_cofins_apuracao_campos enable row level security;
create policy "documentos de apuracao da empresa atribuida" on public.pis_cofins_apuracao_documentos for select using (public.tem_acesso_empresa(empresa_id));
create policy "apuracoes historicas da empresa atribuida" on public.pis_cofins_apuracoes_historicas for select using (public.tem_acesso_empresa(empresa_id));
create policy "campos da apuracao acessivel" on public.pis_cofins_apuracao_campos for select using (exists (
  select 1 from public.pis_cofins_apuracoes_historicas a where a.id = apuracao_id and public.tem_acesso_empresa(a.empresa_id)
));
