-- Estrutura aditiva, vazia e versionada para o comparador de regimes.
-- Não inclui qualquer percentual fiscal, não altera motor ou resultados.
create table if not exists public.param_irpj_csll_versionados (
  id bigint generated by default as identity primary key,
  tributo text not null check (tributo in ('IRPJ','CSLL')),
  regime text not null check (regime in ('lucro_real','lucro_presumido')),
  natureza_receita text not null default 'GERAL',
  tipo_base text not null,
  percentual_base numeric,
  aliquota numeric,
  adicional numeric,
  limite_adicional numeric,
  vigencia_inicio date not null,
  vigencia_fim date,
  fonte text,
  fundamento text,
  versao text not null,
  status text not null default 'RASCUNHO' check (status in ('RASCUNHO','VALIDADO','ATIVO','SUBSTITUIDO','ARQUIVADO','REJEITADO')),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (tributo, regime, natureza_receita, versao, vigencia_inicio)
);
create index if not exists ix_param_irpj_csll_ativo
  on public.param_irpj_csll_versionados (regime, status, vigencia_inicio, vigencia_fim);
