create table if not exists public.pricing_base_operacional (
 id bigint generated by default as identity primary key, empresa_id bigint not null, codigo text not null, descricao text not null, modelo text not null,
 fornecedor_cnpj text, regime_fornecedor text, pis numeric, cofins numeric, valor_aquisicao numeric, prazo_depreciacao_meses integer, valor_residual numeric,
 origem text not null default 'IMPORTACAO', evidencia text, ativo boolean not null default true, criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now(), unique(empresa_id,codigo,modelo)
);
create table if not exists public.pricing_base_estrutura (
 id bigint generated by default as identity primary key, base_operacional_id bigint not null references public.pricing_base_operacional(id) on delete cascade,
 codigo_componente text not null, descricao text not null, tipo_componente text not null, valor numeric not null default 0, pis numeric, cofins numeric,
 fornecedor_cnpj text, regime_fornecedor text, origem text not null default 'IMPORTACAO', evidencia text, criado_em timestamptz not null default now()
);
alter table public.pricing_base_operacional enable row level security;
alter table public.pricing_base_estrutura enable row level security;
