alter table public.receitas_sem_dfe add column if not exists item_receita_chave text;

create table if not exists public.catalogo_itens_receita (
  chave text primary key,
  nome text not null,
  classificacao_fiscal text not null,
  ativo boolean not null default true,
  ordem integer not null default 0,
  criado_em timestamptz default now()
);

create table if not exists public.regras_itens_receita_regime (
  id bigint generated by default as identity primary key,
  item_chave text not null references public.catalogo_itens_receita(chave),
  regime_empresa text not null,
  pis_percentual numeric,
  cofins_percentual numeric,
  tratamento_atual text not null,
  tratamento_reforma text not null,
  fundamento text,
  vigencia_inicio date not null default date '2026-01-01',
  vigencia_fim date,
  ativo boolean not null default true,
  unique(item_chave, regime_empresa, vigencia_inicio)
);
create index if not exists ix_regras_itens_receita_regime on public.regras_itens_receita_regime(item_chave,regime_empresa,ativo,vigencia_inicio desc);

insert into public.catalogo_itens_receita(chave,nome,classificacao_fiscal,ordem) values
 ('LOCACAO_BENS_MOVEIS','Locação de equipamentos / bens móveis','LOCACAO_BEM_MOVEL',1),
 ('ALUGUEL_IMOVEIS_PROPRIOS','Aluguel de imóveis próprios','LOCACAO_IMOVEL',2),
 ('LICENCIAMENTO_SOFTWARE_PROPRIO','Licenciamento / cessão de uso de software próprio','CESSAO_DIREITOS',3),
 ('RECEITAS_FINANCEIRAS_ORDINARIAS','Receitas financeiras ordinárias','RECEITA_FINANCEIRA',4)
on conflict (chave) do nothing;

insert into public.regras_itens_receita_regime(item_chave,regime_empresa,pis_percentual,cofins_percentual,tratamento_atual,tratamento_reforma,fundamento) values
 ('LOCACAO_BENS_MOVEIS','lucro_real',.0165,.076,'Não cumulativo: PIS 1,65% + Cofins 7,60%, salvo exceção específica.','CBS/IBS: tratamento a confirmar pela classificação e legislação vigente.','Regra geral de PIS/Cofins; requer confirmação de exceções.'),
 ('LOCACAO_BENS_MOVEIS','lucro_presumido',.0065,.03,'Cumulativo: PIS 0,65% + Cofins 3,00%.','CBS/IBS: tratamento a confirmar pela classificação e legislação vigente.','Regra geral do regime cumulativo.'),
 ('LOCACAO_BENS_MOVEIS','simples_nacional',null,null,'Receita no DAS; exige segregação adequada (em regra, Anexo III).','CBS/IBS: tratamento a confirmar pela classificação e legislação vigente.','Não calcular PIS/Cofins por fora do DAS.'),
 ('ALUGUEL_IMOVEIS_PROPRIOS','lucro_real',.0165,.076,'Não cumulativo: PIS 1,65% + Cofins 7,60%, salvo hipótese específica.','CBS/IBS: tratamento imobiliário a confirmar pela legislação vigente.','Aplicação depende do enquadramento da receita empresarial.'),
 ('ALUGUEL_IMOVEIS_PROPRIOS','lucro_presumido',.0065,.03,'Cumulativo: PIS 0,65% + Cofins 3,00%.','CBS/IBS: tratamento imobiliário a confirmar pela legislação vigente.','Aplicação depende do enquadramento da receita empresarial.'),
 ('ALUGUEL_IMOVEIS_PROPRIOS','simples_nacional',null,null,'Exige validação: locação de imóveis próprios possui restrições no Simples Nacional.','CBS/IBS: tratamento imobiliário a confirmar pela legislação vigente.','Bloqueado para revisão técnica antes de apurar.'),
 ('LICENCIAMENTO_SOFTWARE_PROPRIO','lucro_real',.0065,.03,'Cumulativo obrigatório, quando enquadrado na hipótese legal aplicável: PIS 0,65% + Cofins 3,00%.','CBS/IBS: tratamento a confirmar pela classificação e legislação vigente.','Lei 10.833/2003, art. 10, XXV; validar enquadramento.'),
 ('LICENCIAMENTO_SOFTWARE_PROPRIO','lucro_presumido',.0065,.03,'Cumulativo: PIS 0,65% + Cofins 3,00%.','CBS/IBS: tratamento a confirmar pela classificação e legislação vigente.','Regra geral do regime cumulativo.'),
 ('LICENCIAMENTO_SOFTWARE_PROPRIO','simples_nacional',null,null,'Receita no DAS; Anexo III ou V conforme fator R e atividade.','CBS/IBS: tratamento a confirmar pela classificação e legislação vigente.','Não calcular PIS/Cofins por fora do DAS.'),
 ('RECEITAS_FINANCEIRAS_ORDINARIAS','lucro_real',.0065,.04,'Receita financeira: PIS 0,65% + Cofins 4,00%, observadas exclusões e exceções.','CBS/IBS: tratamento financeiro a confirmar pela legislação vigente.','Decreto 8.426/2015; validar natureza do rendimento.'),
 ('RECEITAS_FINANCEIRAS_ORDINARIAS','lucro_presumido',null,null,'Em regra, sem incidência quando não constituir atividade/objeto habitual da empresa.','CBS/IBS: tratamento financeiro a confirmar pela legislação vigente.','Exige confirmação da habitualidade.'),
 ('RECEITAS_FINANCEIRAS_ORDINARIAS','simples_nacional',null,null,'Rendimentos de aplicações não integram a base do Simples; não calcular PIS/Cofins separado.','CBS/IBS: tratamento financeiro a confirmar pela legislação vigente.','Exige confirmação da natureza do rendimento.')
on conflict (item_chave,regime_empresa,vigencia_inicio) do nothing;

alter table public.catalogo_itens_receita enable row level security;
alter table public.regras_itens_receita_regime enable row level security;
create policy "catalogo de receitas leitura autenticada" on public.catalogo_itens_receita for select to authenticated using (true);
create policy "regras de receitas leitura autenticada" on public.regras_itens_receita_regime for select to authenticated using (true);
