-- Referências fiscais da empresa analisada, por serviço prestado.
create table if not exists public.empresa_servicos_fiscais (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  chave text not null,
  nbs text,
  descricao text not null,
  pis_cofins numeric,
  das_efetivo numeric,
  iss_aliquota numeric,
  ativo boolean not null default true,
  origem text not null default 'manual',
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (empresa_id, chave)
);

alter table public.empresa_servicos_fiscais enable row level security;
create policy "referencia fiscal da empresa atribuida" on public.empresa_servicos_fiscais
  for select using (public.tem_acesso_empresa(empresa_id));
