-- Histórico da carga da RFB: também é compartilhado, pois o disco do Render
-- não é a fonte de verdade e pode ser recriado a qualquer momento.
create table if not exists public.base_regime_importacoes (
  id bigint generated by default as identity primary key,
  arquivo text not null,
  regime text,
  ano integer,
  linhas integer default 0,
  importados integer default 0,
  invalidos integer default 0,
  duplicados integer default 0,
  segundos numeric,
  criado_em timestamptz not null default now()
);

alter table public.base_regime_importacoes enable row level security;

-- Registra a migração já concluída, sem duplicar o evento em futuras execuções.
insert into public.base_regime_importacoes (arquivo, regime, ano, linhas, importados, invalidos, duplicados, segundos)
select 'Base RFB 2024 — carga compartilhada', r.regime, 2024, r.total, r.total, 0, 0, null
from (
  select string_agg(distinct regime, ', ' order by regime) as regime, count(*)::int as total
  from public.base_regime where ano = 2024
) r
where not exists (select 1 from public.base_regime_importacoes where arquivo = 'Base RFB 2024 — carga compartilhada');
