-- Elegibilidade condicional do Anexo XI: adquirente público (200043) e
-- prestador com sócio brasileiro >= 20% (200044). Dados ausentes ficam NULL.
create table if not exists public.empresa_qsa (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  nome text not null,
  documento text,
  qualificacao text,
  pais text,
  percentual_participacao numeric,
  brasileiro boolean not null default true,
  fonte text,
  consultado_em timestamptz,
  origem text not null default 'consulta_cadastral',
  criado_em timestamptz default now(),
  atualizado_em timestamptz default now(),
  unique (empresa_id, nome, documento, qualificacao)
);
create index if not exists ix_empresa_qsa_empresa on public.empresa_qsa(empresa_id);

create table if not exists public.param_naturezas_juridicas_anexo_xi (
  codigo_natureza_juridica text primary key,
  descricao text not null,
  categoria text not null check (categoria in ('ADMINISTRACAO_DIRETA','AUTARQUIA','FUNDACAO_PUBLICA')),
  elegivel_200043 boolean not null default false,
  fonte text not null,
  versao text not null default '1',
  vigencia_inicio date not null default date '2026-01-01',
  vigencia_fim date,
  status text not null default 'ATIVO',
  atualizado_em timestamptz default now()
);

-- Tabela de natureza jurídica RFB: somente órgãos da administração direta,
-- autarquias e fundações públicas. Empresa pública (201-1) e economia mista
-- (203-8) não são inseridas e, portanto, não confirmam o benefício.
insert into public.param_naturezas_juridicas_anexo_xi
  (codigo_natureza_juridica, descricao, categoria, elegivel_200043, fonte, versao)
values
 ('1015','Órgão Público do Poder Executivo Federal','ADMINISTRACAO_DIRETA',true,'RFB - Tabela de Natureza Jurídica','1'),
 ('1023','Órgão Público do Poder Executivo Estadual ou do Distrito Federal','ADMINISTRACAO_DIRETA',true,'RFB - Tabela de Natureza Jurídica','1'),
 ('1031','Órgão Público do Poder Executivo Municipal','ADMINISTRACAO_DIRETA',true,'RFB - Tabela de Natureza Jurídica','1'),
 ('1040','Órgão Público do Poder Legislativo Federal','ADMINISTRACAO_DIRETA',true,'RFB - Tabela de Natureza Jurídica','1'),
 ('1058','Órgão Público do Poder Legislativo Estadual ou do Distrito Federal','ADMINISTRACAO_DIRETA',true,'RFB - Tabela de Natureza Jurídica','1'),
 ('1066','Órgão Público do Poder Legislativo Municipal','ADMINISTRACAO_DIRETA',true,'RFB - Tabela de Natureza Jurídica','1'),
 ('1074','Órgão Público do Poder Judiciário Federal','ADMINISTRACAO_DIRETA',true,'RFB - Tabela de Natureza Jurídica','1'),
 ('1082','Órgão Público do Poder Judiciário Estadual','ADMINISTRACAO_DIRETA',true,'RFB - Tabela de Natureza Jurídica','1'),
 ('1104','Autarquia Federal','AUTARQUIA',true,'RFB - Tabela de Natureza Jurídica','1'),
 ('1112','Autarquia Estadual ou do Distrito Federal','AUTARQUIA',true,'RFB - Tabela de Natureza Jurídica','1'),
 ('1120','Autarquia Municipal','AUTARQUIA',true,'RFB - Tabela de Natureza Jurídica','1'),
 ('1139','Fundação Pública de Direito Público Federal','FUNDACAO_PUBLICA',true,'RFB - Tabela de Natureza Jurídica','1'),
 ('1147','Fundação Pública de Direito Público Estadual ou do Distrito Federal','FUNDACAO_PUBLICA',true,'RFB - Tabela de Natureza Jurídica','1'),
 ('1155','Fundação Pública de Direito Público Municipal','FUNDACAO_PUBLICA',true,'RFB - Tabela de Natureza Jurídica','1'),
 ('1252','Fundação Pública de Direito Privado Federal','FUNDACAO_PUBLICA',true,'RFB - Tabela de Natureza Jurídica','1'),
 ('1260','Fundação Pública de Direito Privado Estadual ou do Distrito Federal','FUNDACAO_PUBLICA',true,'RFB - Tabela de Natureza Jurídica','1'),
 ('1279','Fundação Pública de Direito Privado Municipal','FUNDACAO_PUBLICA',true,'RFB - Tabela de Natureza Jurídica','1'),
 ('1236','Estado ou Distrito Federal','ADMINISTRACAO_DIRETA',true,'RFB - Tabela de Natureza Jurídica','1'),
 ('1244','Município','ADMINISTRACAO_DIRETA',true,'RFB - Tabela de Natureza Jurídica','1')
on conflict (codigo_natureza_juridica) do update set
 descricao=excluded.descricao, categoria=excluded.categoria,
 elegivel_200043=excluded.elegivel_200043, fonte=excluded.fonte,
 versao=excluded.versao, status='ATIVO', atualizado_em=now();

alter table public.empresa_qsa enable row level security;
alter table public.param_naturezas_juridicas_anexo_xi enable row level security;
