alter table public.receitas_sem_dfe add column if not exists status_motor text default 'PENDENTE_CLASSIFICACAO';
alter table public.receitas_sem_dfe add column if not exists regra_motor_id bigint;
alter table public.receitas_sem_dfe add column if not exists regra_motor_versao integer;
alter table public.receitas_sem_dfe add column if not exists regra_motor_atual text;
alter table public.receitas_sem_dfe add column if not exists regra_motor_reforma text;
alter table public.receitas_sem_dfe add column if not exists cst_motor text;
alter table public.receitas_sem_dfe add column if not exists cclasstrib_motor text;
alter table public.receitas_sem_dfe add column if not exists fundamento_motor text;
alter table public.receitas_sem_dfe add column if not exists pendencia_motor text;
alter table public.receitas_sem_dfe add column if not exists processado_motor_em timestamptz;

create table if not exists public.regras_receitas_sem_dfe (
  id bigint generated by default as identity primary key,
  classificacao_fiscal text not null,
  subtipo text,
  tratamento_atual text,
  tratamento_reforma text,
  cst text,
  cclasstrib text,
  fundamento text,
  vigencia_inicio date not null,
  vigencia_fim date,
  prioridade integer not null default 0,
  versao integer not null default 1,
  status text not null default 'RASCUNHO',
  fonte text not null,
  evidencia text,
  criado_em timestamptz default now(),
  atualizado_em timestamptz default now()
);
create index if not exists ix_regras_receitas_sem_dfe_motor on public.regras_receitas_sem_dfe(status, classificacao_fiscal, subtipo, vigencia_inicio, prioridade desc);
