-- SLA do produto e rastreabilidade das tarefas obrigatórias do projeto.
-- A migração é aditiva: não altera nem remove tarefas já existentes.
create table if not exists public.sla_marcos (
  id bigint generated by default as identity primary key,
  origem_local_id bigint unique,
  chave text not null unique, titulo text not null, prazo_dias integer not null default 0,
  precedencia_chave text, ativo boolean not null default true, ordem integer not null default 0,
  criado_em timestamptz default now(), atualizado_em timestamptz
);
create table if not exists public.sla_tarefas (
  id bigint generated by default as identity primary key,
  origem_local_id bigint unique,
  marco_id bigint not null references public.sla_marcos(id) on delete cascade,
  titulo text not null, descricao text, obrigatoria boolean not null default true,
  ativo boolean not null default true, ordem integer not null default 0
);
alter table public.sla_marcos add column if not exists origem_local_id bigint unique;
alter table public.sla_tarefas add column if not exists origem_local_id bigint unique;
alter table public.projeto_tarefas add column if not exists obrigatoria boolean not null default false;
alter table public.projeto_tarefas add column if not exists sla_marco_id bigint references public.sla_marcos(id);
alter table public.projeto_tarefas add column if not exists prazo_original date;
alter table public.projeto_tarefas add column if not exists prorrogado_em timestamptz;
alter table public.projeto_tarefas add column if not exists justificativa_prorrogacao text;
create table if not exists public.projeto_prorrogacoes_sla (
  id uuid primary key default gen_random_uuid(), projeto_id uuid not null references public.projetos(id) on delete cascade,
  tarefa_id uuid not null references public.projeto_tarefas(id) on delete cascade,
  marco_id bigint not null references public.sla_marcos(id), prazo_anterior date not null, novo_prazo date not null,
  justificativa text not null, usuario_id uuid, criado_em timestamptz default now()
);
create index if not exists ix_projeto_tarefas_sla_marco on public.projeto_tarefas(projeto_id,sla_marco_id);
alter table public.sla_marcos enable row level security;
alter table public.sla_tarefas enable row level security;
alter table public.projeto_prorrogacoes_sla enable row level security;
