create table if not exists public.pricing_premissas_comerciais (
 id bigint generated by default as identity primary key, empresa_id bigint not null, nome text not null,
 margem_contribuicao numeric not null default 0, percentuais_por_dentro numeric not null default 0,
 ativo boolean not null default true, padrao boolean not null default false,
 criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now(), unique(empresa_id,nome)
);
create index if not exists ix_pricing_premissas_empresa on public.pricing_premissas_comerciais(empresa_id,ativo);
alter table public.pricing_premissas_comerciais enable row level security;
