create table if not exists public.documentos_fiscais_cancelamentos (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  data_emissao date not null,
  numero text not null,
  modelo_documento_fiscal text not null,
  serie text not null default '',
  situacao text not null default 'CANCELADO',
  origem text not null default 'QUESTOR_RELATORIO_CANCELADOS',
  evidencia text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (empresa_id, data_emissao, numero, modelo_documento_fiscal, serie)
);
create index if not exists ix_cancelamentos_documentos_empresa
  on public.documentos_fiscais_cancelamentos (empresa_id, data_emissao, numero, modelo_documento_fiscal);
