-- Precificação canônica e versionada. Não altera nem remove bases legadas.
-- Instalações anteriores possuíam produtos sem estes campos auxiliares.
alter table public.pricing_products add column if not exists nbs text;
alter table public.pricing_products add column if not exists lc116 text;
alter table public.pricing_products add column if not exists natureza_item text not null default 'produto';
create table if not exists public.pricing_itens (
  id bigint generated by default as identity primary key, empresa_id bigint not null,
  codigo text not null, descricao text not null, modalidade text not null default 'REVENDA', natureza_item text not null default 'produto',
  ncm text, nbs text, lc116 text, unidade text, perfil_cliente text, preco_atual numeric not null default 0,
  margem_contribuicao numeric not null default 0, percentuais_por_dentro numeric not null default 0,
  ativo boolean not null default true, origem text not null default 'MIGRACAO', origem_tipo text, origem_id bigint,
  criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now(), unique(empresa_id,codigo,modalidade)
);
create table if not exists public.pricing_creditos_globais (
  id bigint generated by default as identity primary key, empresa_id bigint not null, descricao text not null,
  natureza text not null default 'GERENCIAL', valor numeric not null default 0, criterio_rateio text, percentual_rateio numeric,
  vigencia_inicio date, vigencia_fim date, evidencia text, origem text not null default 'MANUAL', ativo boolean not null default true,
  criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now()
);
create table if not exists public.pricing_calculos (
  id bigint generated by default as identity primary key, empresa_id bigint not null, pricing_item_id bigint not null references public.pricing_itens(id) on delete restrict,
  versao integer not null, status text not null default 'DRAFT', modalidade text not null, parametros_json jsonb not null, resultado_json jsonb not null,
  evidencia_json jsonb, origem text not null default 'MOTOR_PRECIFICACAO', calculado_em timestamptz not null default now(), aprovado_em timestamptz, vigente_em timestamptz,
  substituido_por_id bigint references public.pricing_calculos(id), unique(pricing_item_id,versao)
);
create table if not exists public.pricing_calculo_tratamentos (
  id bigint generated by default as identity primary key, pricing_calculo_id bigint not null references public.pricing_calculos(id) on delete cascade,
  tratamento text not null, aliquota_efetiva_cbs numeric, preserva_credito boolean, estorna_credito boolean, resultado_json jsonb not null,
  status text not null default 'CALCULATED', unique(pricing_calculo_id,tratamento)
);
create table if not exists public.pricing_import_linhas (
  id bigint generated by default as identity primary key, lote_id bigint not null references public.pricing_import_batches(id) on delete cascade,
  linha integer not null, aba text, codigo_item text, status text not null, erro text, dados_json jsonb, pricing_item_id bigint references public.pricing_itens(id), criado_em timestamptz not null default now()
);
alter table public.pricing_itens enable row level security;
alter table public.pricing_creditos_globais enable row level security;
alter table public.pricing_calculos enable row level security;
alter table public.pricing_calculo_tratamentos enable row level security;
alter table public.pricing_import_linhas enable row level security;

insert into public.pricing_itens (empresa_id,codigo,descricao,modalidade,natureza_item,ncm,nbs,lc116,unidade,perfil_cliente,preco_atual,origem,origem_tipo,origem_id)
select empresa_id,codigo,descricao,'REVENDA','produto',ncm,nbs,lc116,unidade,perfil_cliente,valor_venda_atual,'MIGRACAO','pricing_products',id from public.pricing_products
on conflict (empresa_id,codigo,modalidade) do nothing;
insert into public.pricing_itens (empresa_id,codigo,descricao,modalidade,natureza_item,ncm,nbs,lc116,unidade,perfil_cliente,preco_atual,origem,origem_tipo,origem_id)
select empresa_id,codigo,descricao,'REVENDA','servico','',nbs,lc116,unidade,perfil_cliente,valor_venda_atual,'MIGRACAO','pricing_services',id from public.pricing_services
on conflict (empresa_id,codigo,modalidade) do nothing;
