create table if not exists public.empresa_prontidao_declaracoes (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  tipo text not null,
  referencia text not null,
  motivo text not null,
  justificativa text,
  usuario_id uuid,
  criado_em timestamptz not null default now(),
  unique(empresa_id,tipo,referencia)
);
create index if not exists ix_empresa_prontidao_declaracoes on public.empresa_prontidao_declaracoes(empresa_id,tipo,referencia);
alter table public.empresa_prontidao_declaracoes enable row level security;
create policy "prontidao_declaracoes_leitura_autenticada" on public.empresa_prontidao_declaracoes for select to authenticated using (true);
