create table if not exists public.empresa_periodo_analisado (
  empresa_id bigint primary key references public.empresas(id) on delete cascade,
  competencia_inicio text not null,
  competencia_fim text not null,
  data_inicio date not null,
  data_fim date not null,
  atualizado_por uuid,
  atualizado_em timestamptz not null default now(),
  check (competencia_inicio ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  check (competencia_fim ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  check (competencia_inicio <= competencia_fim)
);
create table if not exists public.empresa_periodo_analisado_eventos (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  acao text not null,
  usuario_id uuid,
  antes_json jsonb not null default '{}'::jsonb,
  depois_json jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now()
);
create index if not exists ix_empresa_periodo_analisado_eventos on public.empresa_periodo_analisado_eventos(empresa_id,id desc);
alter table public.empresa_periodo_analisado enable row level security;
alter table public.empresa_periodo_analisado_eventos enable row level security;
create policy "periodo_analisado_leitura_autenticada" on public.empresa_periodo_analisado for select to authenticated using (true);
create policy "periodo_analisado_eventos_leitura_autenticada" on public.empresa_periodo_analisado_eventos for select to authenticated using (true);

-- Janela de apurações por empresa: pelo menos 12 competências. Quando não
-- inclui o exercício, a janela termina no mês anterior ao início do exercício.
alter table public.empresa_periodo_analisado add column if not exists apuracao_meses integer not null default 12 check (apuracao_meses >= 12);
alter table public.empresa_periodo_analisado add column if not exists apuracao_inclui_exercicio boolean not null default true;
