-- Etapa 2Y: auditoria imutável do retro-link operacional para catálogo oficial.
-- Não altera movimentos, motor_resultados_operacionais ou catálogo ativo.

create table if not exists public.base_servicos_catalogo_lineage (
  id bigint generated by default as identity primary key,
  base_servicos_id bigint not null references public.base_servicos(id) on delete restrict,
  catalogo_versao_id bigint not null references public.catalogo_versoes(id) on delete restrict,
  catalogo_linha_id bigint not null,
  status text not null check (status in (
    'LINK_EXATO', 'LINK_UNICO_POR_VARIANTE', 'MULTIPLOS_CANDIDATOS',
    'SEM_CORRESPONDENCIA', 'DIVERGENCIA_SEMANTICA'
  )),
  chave_variante text not null,
  criterios jsonb not null default '{}'::jsonb,
  hash_decisao_sha256 text not null,
  registrado_em timestamptz not null default now(),
  foreign key (catalogo_linha_id, catalogo_versao_id)
    references public.catalogo_linhas_versoes(id, catalogo_versao_id) on delete restrict,
  unique (base_servicos_id, catalogo_versao_id, catalogo_linha_id)
);

create index if not exists ix_base_servicos_catalogo_lineage_base
  on public.base_servicos_catalogo_lineage(base_servicos_id);
create index if not exists ix_base_servicos_catalogo_lineage_catalogo
  on public.base_servicos_catalogo_lineage(catalogo_versao_id, catalogo_linha_id);
