-- Contratos — Entrega 1
-- Estrutura preparada para a publicação futura. Não executa nenhum cálculo
-- tributário e não altera contratos existentes.
alter table public.contratos add column if not exists nome text;
alter table public.contratos add column if not exists moeda text default 'BRL';
alter table public.contratos add column if not exists periodicidade_reajuste text;
alter table public.contratos add column if not exists tipo_relacao text;
alter table public.contratos add column if not exists renovacao text;
alter table public.contratos add column if not exists observacoes text;
alter table public.contratos add column if not exists arquivo_origem text;
alter table public.contratos add column if not exists status_analise text default 'NAO_INICIADA';
alter table public.contratos add column if not exists natureza_contrato text default 'INDETERMINADO';
alter table public.contratos add column if not exists natureza_contrato_origem text;
alter table public.contratos add column if not exists natureza_contrato_evidencia text;

create table if not exists public.contrato_documentos (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  contrato_id bigint not null references public.contratos(id) on delete cascade,
  nome_original text not null, mime_type text, tipo_origem text not null,
  conteudo_original bytea, hash_original text, tamanho_bytes bigint default 0,
  texto_extraido text, status_extracao text default 'PENDENTE',
  observacao_extracao text, criado_em timestamptz default now()
);
create index if not exists ix_contrato_documentos_contrato on public.contrato_documentos(contrato_id);

create table if not exists public.contrato_clausulas_extraidas (
  id bigint generated by default as identity primary key,
  documento_id bigint not null references public.contrato_documentos(id) on delete cascade,
  contrato_id bigint not null references public.contratos(id) on delete cascade,
  ordem integer not null, texto_original text not null, localizacao text not null,
  pagina integer, secao text, tema text not null, confianca numeric default 1,
  natureza text not null default 'EXTRAIDO', criado_em timestamptz default now()
);
create index if not exists ix_contrato_clausulas_documento on public.contrato_clausulas_extraidas(documento_id, ordem);

create table if not exists public.contrato_riscos_iniciais (
  id bigint generated by default as identity primary key,
  documento_id bigint not null references public.contrato_documentos(id) on delete cascade,
  contrato_id bigint not null references public.contratos(id) on delete cascade,
  clausula_id bigint references public.contrato_clausulas_extraidas(id) on delete set null,
  codigo text not null, risco text not null, evidencia text not null,
  impacto_potencial text not null, nivel text not null, fundamento text not null,
  natureza text not null default 'INTERPRETADO', status text default 'ABERTO', criado_em timestamptz default now()
);
create index if not exists ix_contrato_riscos_documento on public.contrato_riscos_iniciais(documento_id);

create table if not exists public.contrato_precificacao_vinculos (
  id bigint generated by default as identity primary key,
  contrato_id bigint not null references public.contratos(id) on delete cascade,
  tipo_item text not null check(tipo_item in ('produto','servico')),
  item_precificacao_id bigint not null,
  status text not null default 'PENDENTE_CONFIRMACAO', origem text not null default 'EXPLICITO',
  observacoes text, confirmado_em timestamptz, criado_em timestamptz default now(),
  unique(contrato_id,tipo_item,item_precificacao_id)
);

create table if not exists public.pricing_simulacoes (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  modo text not null, parametros_json jsonb, resultados_json jsonb not null,
  origem text not null default 'MOTOR_FISCAL_OFICIAL', natureza text not null default 'CALCULADO',
  criado_em timestamptz default now()
);
create index if not exists ix_pricing_simulacoes_empresa on public.pricing_simulacoes(empresa_id, id desc);
alter table public.contrato_precificacao_vinculos add column if not exists pricing_simulacao_id bigint references public.pricing_simulacoes(id) on delete set null;

create table if not exists public.contrato_recomendacoes (
  id bigint generated by default as identity primary key,
  contrato_id bigint not null references public.contratos(id) on delete cascade,
  risco_id bigint references public.contrato_riscos_iniciais(id) on delete set null,
  clausula_id bigint references public.contrato_clausulas_extraidas(id) on delete set null,
  recomendacao text not null, evidencia text not null, impacto_potencial text not null,
  prioridade text not null check(prioridade in ('ALTA','MEDIA','BAIXA')),
  fundamento text not null, natureza text not null default 'INTERPRETADO',
  origem text not null default 'TRIAGEM_CONTRATUAL', criado_em timestamptz default now()
);
create index if not exists ix_contrato_recomendacoes_contrato on public.contrato_recomendacoes(contrato_id);

create table if not exists public.contrato_sugestoes_clausulas (
  id bigint generated by default as identity primary key,
  contrato_id bigint not null references public.contratos(id) on delete cascade,
  risco_id bigint references public.contrato_riscos_iniciais(id) on delete set null,
  clausula_original text, sugestao_redacao text not null, motivo text not null,
  impacto_esperado text not null, fundamento text not null,
  natureza text not null default 'SUGERIDO', status text default 'RASCUNHO', criado_em timestamptz default now()
);
create index if not exists ix_contrato_sugestoes_contrato on public.contrato_sugestoes_clausulas(contrato_id);
