-- Sattva | Base compartilhada de gestão de escopo e entregas
-- Execute após 20260823_usuarios_projetos.sql.

create table if not exists public.empresas (
  id bigint generated by default as identity primary key,
  origem_local_id bigint unique,
  cnpj text unique not null,
  razao_social text not null,
  nome_fantasia text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.projetos (
  id uuid primary key default gen_random_uuid(),
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  origem_local_contratacao_id bigint unique,
  nome_plano text not null default 'Escopo personalizado',
  escopo jsonb not null default '[]'::jsonb,
  status text not null default 'aguardando_aprovacao' check (status in ('aguardando_aprovacao', 'em_execucao', 'concluido', 'cancelado')),
  acompanhamento_meses integer not null default 3 check (acompanhamento_meses between 0 and 36),
  competencia_referencia text,
  aprovado_em timestamptz,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.projeto_entregas (
  id uuid primary key default gen_random_uuid(),
  projeto_id uuid not null references public.projetos(id) on delete cascade,
  origem_local_id bigint unique,
  chave text not null,
  titulo text not null,
  status text not null default 'pendente' check (status in ('pendente', 'em_andamento', 'concluida', 'nao_aplicavel')),
  concluido_em timestamptz,
  observacoes text,
  unique (projeto_id, chave)
);

create table if not exists public.projeto_acompanhamentos (
  id uuid primary key default gen_random_uuid(),
  projeto_id uuid not null references public.projetos(id) on delete cascade,
  origem_local_id bigint unique,
  competencia text not null,
  nome text,
  status text not null default 'planejado' check (status in ('planejado', 'em_andamento', 'concluido')),
  observacoes text,
  unique (projeto_id, competencia)
);

alter table public.empresas enable row level security;
alter table public.projetos enable row level security;
alter table public.projeto_entregas enable row level security;
alter table public.projeto_acompanhamentos enable row level security;

create policy "empresa atribuida" on public.empresas for select using (public.tem_acesso_empresa(id));
create policy "projeto da empresa atribuida" on public.projetos for select using (public.tem_acesso_empresa(empresa_id));
create policy "entrega da empresa atribuida" on public.projeto_entregas for select using (
  exists (select 1 from public.projetos p where p.id = projeto_id and public.tem_acesso_empresa(p.empresa_id))
);
create policy "acompanhamento da empresa atribuida" on public.projeto_acompanhamentos for select using (
  exists (select 1 from public.projetos p where p.id = projeto_id and public.tem_acesso_empresa(p.empresa_id))
);
