-- Fase 2A: estruturas de evidência e cobertura. Não contém fórmula tributária.

create table if not exists public.cadastro_produtos_mestre (
  id bigint primary key, chave text not null unique, sku text, gtin text, descricao text, ncm text, cest text, unidade text,
  papel_cadeia text default 'INDETERMINADO', tratamento_conhecido text, vigencia_inicio text, vigencia_fim text,
  origem text, evidencia text, status text default 'ATIVO', atualizado_em timestamptz
);
create index if not exists ix_cadastro_produtos_mestre_ncm on public.cadastro_produtos_mestre(ncm);

create table if not exists public.cadastro_servicos_mestre (
  id bigint primary key, chave text not null unique, codigo_interno text, descricao text, nbs text, lc116 text, municipio text,
  natureza_servico text, referencia_fiscal text, tratamento_conhecido text, condicoes text, vigencia_inicio text, vigencia_fim text,
  origem text, evidencia text, status text default 'ATIVO', atualizado_em timestamptz
);
create index if not exists ix_cadastro_servicos_mestre_nbs on public.cadastro_servicos_mestre(nbs);

create table if not exists public.regras_enquadramento (
  id text primary key, familia text not null, subfamilia text, tipo_operacao text, direcao text,
  perfil_fornecedor text, perfil_adquirente text, regime_fornecedor text, regime_adquirente text,
  ncm text, nbs text, cclasstrib text, cst text, cfop text, papel_cadeia text, unidade text,
  condicoes_obrigatorias text, condicoes_excludentes text, tratamento_resultante text, formula_id text,
  fundamento_legal text, vigencia_inicio text, vigencia_fim text, prioridade integer not null default 0,
  versao integer not null default 1, status text not null default 'RASCUNHO', fonte text, evidencia text,
  criado_em timestamptz, atualizado_em timestamptz
);
create index if not exists ix_regras_enquadramento_busca on public.regras_enquadramento(status, familia, ncm, nbs, prioridade desc);

create table if not exists public.hipoteses_credito_presumido (
  hipotese_id text primary key, familia text, tipo_operacao text, perfil_fornecedor text, perfil_adquirente text,
  condicoes text, base_calculo text, percentual numeric, formula text, limite text, vigencia_inicio text, vigencia_fim text,
  fundamento_legal text, cclasstrib text, tipo_credito text default 'PRESUMIDO', status text default 'RASCUNHO',
  fonte text, evidencia text, atualizado_em timestamptz
);

create table if not exists public.cobertura_fotografias (
  id bigint generated by default as identity primary key, empresa_id bigint not null, execucao_id bigint,
  tipo text not null default 'FASE_2A', dados jsonb not null, criado_em timestamptz default now()
);
create index if not exists ix_cobertura_fotografias_empresa on public.cobertura_fotografias(empresa_id, criado_em desc);

alter table public.cadastro_produtos_mestre enable row level security;
alter table public.cadastro_servicos_mestre enable row level security;
alter table public.regras_enquadramento enable row level security;
alter table public.hipoteses_credito_presumido enable row level security;
alter table public.cobertura_fotografias enable row level security;

-- O servidor utiliza a service key. Nenhuma política pública é criada aqui.
