create table if not exists public.regras_governo (
  id bigint generated by default as identity primary key,
  tipo text not null, chave text not null, lc116 text, nbs text, ncm text,
  descricao text, tratamento text, cst text, cclasstrib text, indop text,
  reducao numeric, aliquota_zero boolean default false, ente_elegivel text,
  condicoes text, fundamento text, vigencia text, fonte text,
  unique(tipo, chave, cclasstrib)
);
alter table public.regras_governo enable row level security;
