-- Fase 4B: fatos e premissas complementares para diagnóstico.
-- Estas tabelas não alteram movimentos, motor, CBS ou resultados persistidos.
create table if not exists public.folhas_pagamento_competencias (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  competencia text not null,
  valor_folha numeric not null check (valor_folha >= 0),
  pro_labore numeric check (pro_labore is null or pro_labore >= 0),
  origem text not null default 'MANUAL',
  referencia_arquivo text,
  status_validacao text not null default 'PENDENTE',
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (empresa_id, competencia)
);
create index if not exists ix_folhas_pagamento_empresa_competencia
  on public.folhas_pagamento_competencias(empresa_id, competencia desc);

create table if not exists public.margens_operacionais_premissas (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  periodo_inicio text not null,
  periodo_fim text not null,
  margem_operacional_percentual numeric not null check (margem_operacional_percentual >= 0 and margem_operacional_percentual <= 100),
  origem text not null default 'MANUAL',
  natureza text not null default 'PREMISSA_INFORMADA',
  status_validacao text not null default 'PENDENTE',
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (empresa_id, periodo_inicio, periodo_fim)
);
create index if not exists ix_margens_operacionais_empresa_periodo
  on public.margens_operacionais_premissas(empresa_id, periodo_inicio desc, periodo_fim desc);

create table if not exists public.receitas_sem_dfe (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id) on delete cascade,
  competencia text not null,
  tipo_receita text not null,
  descricao text not null,
  valor numeric not null check (valor >= 0),
  origem text not null default 'MANUAL',
  evidencia text,
  status_validacao text not null default 'PENDENTE',
  chave_deduplicacao text not null,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (empresa_id, chave_deduplicacao)
);
create index if not exists ix_receitas_sem_dfe_empresa_competencia
  on public.receitas_sem_dfe(empresa_id, competencia desc);

alter table public.folhas_pagamento_competencias enable row level security;
alter table public.margens_operacionais_premissas enable row level security;
alter table public.receitas_sem_dfe enable row level security;

create policy "folhas da empresa atribuida" on public.folhas_pagamento_competencias for select using (public.tem_acesso_empresa(empresa_id));
create policy "margens da empresa atribuida" on public.margens_operacionais_premissas for select using (public.tem_acesso_empresa(empresa_id));
create policy "receitas complementares da empresa atribuida" on public.receitas_sem_dfe for select using (public.tem_acesso_empresa(empresa_id));
