-- Retenção segura da fila operacional. Não executa limpeza ao ser aplicada.
-- A função remove somente eventos antigos já dispensáveis por todos os
-- consumidores ativos; consumidores novos continuam exigindo carga-base.

create table if not exists public.sincronizacao_operacional_retencao (
  chave text primary key,
  dias_retencao integer not null check (dias_retencao between 7 and 3650),
  consumidor_ativo_horas integer not null check (consumidor_ativo_horas between 1 and 720),
  tamanho_lote integer not null check (tamanho_lote between 100 and 100000),
  atualizado_em timestamptz not null default clock_timestamp()
);

insert into public.sincronizacao_operacional_retencao(chave,dias_retencao,consumidor_ativo_horas,tamanho_lote)
values ('eventos',30,24,10000)
on conflict (chave) do nothing;

alter table public.sincronizacao_operacional_retencao enable row level security;
revoke all on public.sincronizacao_operacional_retencao from anon, authenticated;
grant select on public.sincronizacao_operacional_retencao to service_role;

create table if not exists public.sincronizacao_operacional_arquivos (
  id bigint generated by default as identity primary key,
  tabela text not null,
  sequencia_inicial bigint not null,
  sequencia_final bigint not null,
  linhas bigint not null check (linhas > 0),
  bytes_arquivo bigint not null check (bytes_arquivo > 0),
  sha256_manifesto_partes text not null check (sha256_manifesto_partes ~ '^[0-9a-f]{64}$'),
  armazenamento text not null,
  gerado_em timestamptz not null,
  validado_em timestamptz not null,
  removido_em timestamptz,
  unique(tabela,sequencia_inicial,sequencia_final)
);
alter table public.sincronizacao_operacional_arquivos enable row level security;
revoke all on public.sincronizacao_operacional_arquivos from anon, authenticated;
grant select on public.sincronizacao_operacional_arquivos to service_role;

create or replace function public.limpar_eventos_sincronizacao_operacional(
  p_limite integer default null
) returns table(removidos integer, sequencia_maxima_removida bigint)
language plpgsql
security definer
set search_path=public,pg_catalog
as $$
declare
  politica public.sincronizacao_operacional_retencao%rowtype;
  corte_tecnico bigint;
  checkpoint_ativo bigint;
  limite_lote integer;
begin
  select * into politica from public.sincronizacao_operacional_retencao where chave='eventos' for update;
  if not found then raise exception 'Política de retenção não configurada.'; end if;
  limite_lote:=least(coalesce(p_limite,politica.tamanho_lote),politica.tamanho_lote);
  if limite_lote<1 then raise exception 'Limite inválido.'; end if;
  -- Uma identidade que ficou inativa além da janela não pode reaparecer com
  -- checkpoint antigo depois que a retenção avançou: ela volta por carga-base.
  update public.sincronizacao_operacional_consumidores
     set requer_carga_base=true,sessao_id=null,lease_expira_em=null,atualizado_em=clock_timestamp()
   where requer_carga_base is false
     and ultimo_heartbeat < clock_timestamp()-make_interval(hours=>politica.consumidor_ativo_horas);
  select corte_sequencia_tecnica into corte_tecnico from public.sincronizacao_operacional_estado where chave='fila_v2';
  select min(sequencia_confirmada) into checkpoint_ativo
    from public.sincronizacao_operacional_consumidores
   where requer_carga_base is false;
  -- Sem consumidor ativo não há comprovação suficiente para avançar a retenção v2.
  with candidatas as materialized (
    select sequencia
      from public.sincronizacao_operacional_eventos
     where ocorrido_em < clock_timestamp()-make_interval(days=>politica.dias_retencao)
       and (sequencia<=corte_tecnico or (checkpoint_ativo is not null and sequencia_consumo<=checkpoint_ativo))
     order by sequencia
     limit limite_lote
     for update skip locked
  ), apagadas as (
    delete from public.sincronizacao_operacional_eventos e using candidatas c
     where e.sequencia=c.sequencia
     returning e.sequencia
  )
  select count(*)::integer,max(sequencia) into removidos,sequencia_maxima_removida from apagadas;
  return next;
end;
$$;

revoke all on function public.limpar_eventos_sincronizacao_operacional(integer) from public;
grant execute on function public.limpar_eventos_sincronizacao_operacional(integer) to service_role;
