-- Etapa 2A: telemetria operacional. A migration é exclusivamente aditiva e
-- não toca em fórmulas, memória fiscal nem resultados já calculados.

ALTER TABLE public.motor_resultados_operacionais
  ADD COLUMN IF NOT EXISTS estado_autonomia text,
  ADD COLUMN IF NOT EXISTS codigo_causa text,
  ADD COLUMN IF NOT EXISTS origem_resolucao text,
  ADD COLUMN IF NOT EXISTS evidencia_utilizada text,
  ADD COLUMN IF NOT EXISTS regra_vencedora text,
  ADD COLUMN IF NOT EXISTS requer_intervencao_humana boolean,
  ADD COLUMN IF NOT EXISTS motivo_intervencao text;

CREATE TABLE IF NOT EXISTS public.telemetria_autonomia_execucoes (
  execucao_id bigint PRIMARY KEY REFERENCES public.motor_execucoes_operacionais(id) ON DELETE CASCADE,
  empresa_id bigint NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  meta_autonomia numeric NOT NULL DEFAULT 0.95,
  total_operacoes integer NOT NULL DEFAULT 0,
  operacoes_autonomas integer NOT NULL DEFAULT 0,
  operacoes_intervencao integer NOT NULL DEFAULT 0,
  taxa_autonomia numeric,
  taxa_determinacao numeric,
  taxa_simulacao numeric,
  taxa_indeterminacao_automatica numeric,
  taxa_intervencao_humana numeric,
  estados_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_telemetria_autonomia_empresa_execucao
  ON public.telemetria_autonomia_execucoes(empresa_id, execucao_id DESC);

-- Snapshot por execução, separado da tabela legado excecoes_motor. Assim uma
-- pendência histórica nunca volta a parecer aberta na fotografia ativa.
CREATE TABLE IF NOT EXISTS public.excecoes_motor_execucoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  execucao_id bigint NOT NULL REFERENCES public.motor_execucoes_operacionais(id) ON DELETE CASCADE,
  movimento_id bigint,
  codigo text NOT NULL,
  categoria text NOT NULL,
  gravidade text NOT NULL DEFAULT 'media',
  status text NOT NULL DEFAULT 'ABERTA',
  natureza text NOT NULL DEFAULT 'INDETERMINADO',
  origem text NOT NULL DEFAULT 'MOTOR',
  valor_envolvido numeric NOT NULL DEFAULT 0,
  impacto_cbs_estimado numeric,
  materialidade numeric NOT NULL DEFAULT 0,
  detalhe jsonb,
  criado_em timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_excecao_motor_por_execucao UNIQUE (empresa_id, execucao_id, movimento_id, codigo)
);
CREATE INDEX IF NOT EXISTS ix_excecoes_motor_execucao_ativa
  ON public.excecoes_motor_execucoes(empresa_id, execucao_id, status, materialidade DESC);

ALTER TABLE public.telemetria_autonomia_execucoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.excecoes_motor_execucoes ENABLE ROW LEVEL SECURITY;
