-- Base própria do módulo Precificação e Margem. Não utiliza movimentos do
-- diagnóstico, nem cria qualquer relacionamento fiscal automático.
create table if not exists pricing_products (
  id bigint generated by default as identity primary key, empresa_id bigint not null,
  codigo text not null, descricao text not null, ncm text, unidade text,
  quantidade_producao numeric not null default 1, valor_venda_atual numeric not null default 0,
  custo_direto numeric not null default 0, perfil_cliente text, ativo boolean not null default true,
  origem text not null default 'IMPORTACAO', criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now(),
  unique (empresa_id,codigo)
);
create table if not exists pricing_services (
  id bigint generated by default as identity primary key, empresa_id bigint not null,
  codigo text not null, descricao text not null, lc116 text, nbs text, unidade text,
  quantidade_producao numeric not null default 1, valor_venda_atual numeric not null default 0,
  custo_direto numeric not null default 0, perfil_cliente text, ativo boolean not null default true,
  origem text not null default 'IMPORTACAO', criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now(),
  unique (empresa_id,codigo)
);
create table if not exists pricing_components (
  id bigint generated by default as identity primary key, empresa_id bigint not null,
  produto_saida_id bigint references pricing_products(id) on delete cascade,
  servico_saida_id bigint references pricing_services(id) on delete cascade,
  codigo_componente text not null, descricao text not null, tipo_componente text not null,
  ncm text, nbs text, lc116 text, cnpj_fornecedor text, regime_fornecedor text,
  quantidade numeric not null default 1, custo_unitario_bruto numeric not null default 0,
  perda_percentual numeric not null default 0, ativo boolean not null default true,
  origem text not null default 'IMPORTACAO', criado_em timestamptz not null default now(), atualizado_em timestamptz not null default now(),
  check ((produto_saida_id is not null)::int + (servico_saida_id is not null)::int = 1)
);
create table if not exists pricing_import_batches (
  id bigint generated by default as identity primary key, empresa_id bigint not null,
  arquivo text, status text not null, resumo jsonb, criado_em timestamptz not null default now()
);
alter table pricing_products enable row level security;
alter table pricing_services enable row level security;
alter table pricing_components enable row level security;
alter table pricing_import_batches enable row level security;
